mods.ItemStages.stageModItems("agriculture", "agricraft");

mods.ItemStages.removeItemStage(<agricraft:agri_nugget:10>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:11>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:8>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:7>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:6>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:5>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:3>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget:1>);
mods.ItemStages.removeItemStage(<agricraft:agri_nugget>);



mods.ItemStages.addItemStage("agriculture", <composter:compost>);
mods.ItemStages.addItemStage("agriculture", <composter:compost_bin>);
mods.ItemStages.addItemStage("agriculture", <endercrop:ender_crop>);
mods.ItemStages.addItemStage("agriculture", <endercrop:ender_seeds>);
mods.ItemStages.addItemStage("agriculture", <endercrop:tilled_end_stone>);
mods.ItemStages.addItemStage("agriculture", <astikorcarts:plowcart>);
mods.ItemStages.addItemStage("agriculture", <ancientwarfarevehicle:ammo_cluster_shot_30> );
mods.ItemStages.addItemStage("agriculture", <ancientwarfarevehicle:ammo_explosive_shot_45> );
mods.ItemStages.addItemStage("agriculture", <ancientwarfarevehicle:ammo_hwacha_rocket_explosive> );
mods.ItemStages.addItemStage("agriculture", <astikorcarts:plowcart> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:agaveseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:amaranthseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:arrowrootseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:artichokeseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:asparagusseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:bambooshootseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:barleyseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:beanseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:beetseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:bellpepperseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:blackberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:blueberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:broccoliseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:brusselsproutseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cabbageseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cactusfruitseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:candleberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cantaloupeseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cassavaseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cauliflowerseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:celeryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:chickpeaseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:chilipepperseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:coffeeseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cornseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cottonseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cranberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:cucumberseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:curryleafseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:eggplantseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:elderberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:flaxseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:gigapickleseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:gingerseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:huckleberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:jicamaseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:juniperberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:juteseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:kaleseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:kenafseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:kiwiseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:kohlrabiseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:leekseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:lentilseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:lettuceseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:milletseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:mulberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:mustardseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:oatsseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:okraseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:onionseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:parsnipseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:peanutseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:peasseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:pineappleseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:quinoaseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:radishseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:raspberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:rhubarbseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:riceseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:rutabagaseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:ryeseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:scallionseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:seaweedseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:sesameseedsseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:sisalseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:soybeanseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:spiceleafseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:spinachseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:strawberryseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:sunflowerseedsitem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:sweetpotatoseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:taroseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:tomatilloseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:turnipseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:waterchestnutseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:whitemushroomseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:wintersquashseeditem> );
mods.ItemStages.addItemStage("agriculture", <harvestcraft:zucchiniseeditem> );
mods.ItemStages.addItemStage("agriculture", <minecraft:beetroot_seeds> );
mods.ItemStages.addItemStage("agriculture", <roots:elemental_soil> );
mods.ItemStages.addItemStage("agriculture", <roots:elemental_soil_air> );
mods.ItemStages.addItemStage("agriculture", <roots:elemental_soil_earth> );
mods.ItemStages.addItemStage("agriculture", <roots:elemental_soil_fire> );
mods.ItemStages.addItemStage("agriculture", <roots:elemental_soil_water> );
mods.ItemStages.addItemStage("agriculture", <t3s4ebw:magic_seed> );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "nagascale"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "steeleaf"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "fierymetal"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "knightmetal"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "wood"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "stone"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "flint"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "cactus"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "bone"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "obsidian"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "prismarine"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "endstone"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "sponge"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "firewood"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "iron"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "pigiron"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "knightslime"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "slime"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "blueslime"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "magmaslime"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "netherrack"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "cobalt"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ardite"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "manyullyn"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "copper"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "bronze"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "lead"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "silver"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "electrum"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "steel"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "bread_mat"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "neptunium"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "cheese"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "cold_iron"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "treatedwood"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "constantan"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_glowstone"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_zinc"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_titanium"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_iridium"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_aluminum"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_platinum"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_invar"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_amethyst"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_ruby"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_sapphire"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_peridot"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_osmium"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_refined_obsidian"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_refined_glowstone"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_runestone"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_thaumium"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_lavium"}) );
mods.ItemStages.addItemStage("agriculture", <tconstruct:scythe_head>.withTag({Material: "ref_qivium"}) );
mods.ItemStages.addItemStage("agriculture", <primal:quartz_hoe>);
mods.ItemStages.addItemStage("agriculture", <primal:diamond_hoe>);
mods.ItemStages.addItemStage("agriculture", <primal:emerald_hoe>);
mods.ItemStages.addItemStage("agriculture", <primal:opal_hoe>);
mods.ItemStages.addItemStage("agriculture", <primal:obsidian_hoe>);

/*
//not sure where this recipe went
recipes.addShaped("flint_hoe2", <primal:flint_hoe>,[
    [<primal:flint_knapp>, <ore:cordageGeneral>],
    [<ore:stickWood>, null]
]);

//not sure where this recipe went
recipes.addShaped("bone_hoe2", <primal:bone_hoe>,[
    [<primal:bone_knapp>, <ore:cordageGeneral>],
    [<ore:stickWood>, null]
]);
*/

//mods.recipestages.Recipes.setRecipeStage("agriculture", "flint_hoe2");
mods.recipestages.Recipes.setRecipeStage("agriculture", "flint_hoe");
mods.recipestages.Recipes.setRecipeStage("agriculture", "bone_hoe");
//mods.recipestages.Recipes.setRecipeStage("agriculture", "bone_hoe2");