mods.ItemStages.addItemStage("archery", <minecraft:arrow>);
mods.ItemStages.addItemStage("archery", <minecraft:bow>);
mods.ItemStages.addItemStage("archery", <betterwithmods:composite_bow>);
mods.ItemStages.addItemStage("archery", <ancientwarfareautomation:worksite_upgrade:10> );
mods.ItemStages.addItemStage("archery", <ancientwarfarenpc:bard_instrument:1> );
mods.ItemStages.addItemStage("archery", <ancientwarfarenpc:bard_instrument:2> );
mods.ItemStages.addItemStage("archery", <ancientwarfarenpc:bard_instrument:3> );
mods.ItemStages.addItemStage("archery", <ancientwarfarenpc:combat_order> );
mods.ItemStages.addItemStage("archery", <betterwithmods:composite_bow> );
mods.ItemStages.addItemStage("archery", <grimoireofgaia:bag_arrow> );
mods.ItemStages.addItemStage("archery", <minecraft:arrow> );
mods.ItemStages.addItemStage("archery", <minecraft:bow> );
mods.ItemStages.addItemStage("archery", <minecraft:spectral_arrow> );
mods.ItemStages.addItemStage("archery", <primal:arrow_bitumen> );
mods.ItemStages.addItemStage("archery", <primal:arrow_ironwood> );
mods.ItemStages.addItemStage("archery", <primal:arrow_paraffin> );
mods.ItemStages.addItemStage("archery", <primal:arrow_quartz> );
mods.ItemStages.addItemStage("archery", <primal:arrow_torch_nether> );
mods.ItemStages.addItemStage("archery", <primal:arrow_torch_redstone> );
mods.ItemStages.addItemStage("archery", <primal:arrow_torch_wood> );
mods.ItemStages.addItemStage("archery", <primal:arrow_water> );
mods.ItemStages.addItemStage("archery", <quark:arrow_ender> );
mods.ItemStages.addItemStage("archery", <quark:arrow_explosive> );
mods.ItemStages.addItemStage("archery", <quark:arrow_torch> );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "nagascale"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "steeleaf"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "fierymetal"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "knightmetal"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "wood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "stone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "flint"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "cactus"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "bone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "obsidian"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "prismarine"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "endstone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "sponge"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "firewood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "iron"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "pigiron"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "knightslime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "slime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "blueslime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "magmaslime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "netherrack"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "cobalt"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ardite"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "manyullyn"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "copper"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "bronze"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "lead"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "silver"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "electrum"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "steel"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "neptunium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "cold_iron"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "treatedwood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "constantan"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_glowstone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_zinc"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_titanium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_iridium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_aluminum"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_platinum"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_invar"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_amethyst"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_ruby"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_sapphire"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_peridot"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_osmium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_refined_obsidian"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_refined_glowstone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_runestone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_thaumium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_lavium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_head>.withTag({Material: "ref_qivium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "nagascale"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "steeleaf"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "fierymetal"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "wood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "bone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "blaze"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "reed"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "ice"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "endrod"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "treatedwood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:arrow_shaft>.withTag({Material: "ref_runestone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["nagascale", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["steeleaf", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["fierymetal", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["wood", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["bone", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["blaze", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["reed", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["ice", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["endrod", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["treatedwood", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bolt_core>.withTag({TinkerData: {Materials: ["ref_runestone", "iron"]}}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "nagascale"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "steeleaf"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "fierymetal"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "wood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "stone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "flint"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "cactus"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "bone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "obsidian"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "prismarine"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "endstone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "sponge"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "firewood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "iron"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "pigiron"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "knightslime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "slime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "blueslime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "magmaslime"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "netherrack"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "cobalt"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ardite"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "manyullyn"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "copper"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "bronze"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "lead"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "silver"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "electrum"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "steel"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "treatedwood"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "constantan"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_glowstone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_zinc"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_titanium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_iridium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_aluminum"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_platinum"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_invar"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_amethyst"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_ruby"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_sapphire"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_peridot"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_osmium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_refined_obsidian"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_refined_glowstone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_thaumium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_lavium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_limb>.withTag({Material: "ref_qivium"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_string>.withTag({Material: "string"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_string>.withTag({Material: "slimevine_blue"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_string>.withTag({Material: "slimevine_purple"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_string>.withTag({Material: "vine"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_string>.withTag({Material: "hemp"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:bow_string>.withTag({Material: "ref_runestone"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "steeleaf"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "raven_feather"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "feather"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "slimeleaf_blue"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "slimeleaf_orange"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "slimeleaf_purple"}) );
mods.ItemStages.addItemStage("archery", <tconstruct:fletching>.withTag({Material: "leaf"}) );