

mods.ItemStages.addItemStage("industrial", <bibliocraft:printingpress>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:printplate>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typesettingtable>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:1>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:2>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:3>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:4>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:5>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:6>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:7>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:8>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:9>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:10>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:11>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:12>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:13>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:14>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:typewriter:15>);
mods.ItemStages.addItemStage("industrial", <bibliocraft:enchantedplate>);
mods.ItemStages.addItemStage("industrial", <conarm:travel_goggles>);
mods.ItemStages.addItemStage("industrial", <conarm:travel_goggles_base>);
mods.ItemStages.addItemStage("industrial", <conarm:travel_night>);
mods.ItemStages.stageModItems("industrial","davincisvessels");
mods.ItemStages.stageModItems("industrial","immersiveengineering");
mods.ItemStages.stageModItems("industrial","thaumcraft");
mods.ItemStages.stageModItems("industrial","immersivetech");
mods.ItemStages.stageModItems("industrial","immersivecables");
mods.ItemStages.stageModItems("industrial","travelersbackpack");
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_concrete>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_concrete_ornate>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_concrete_reinforced>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_steel>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_steel_ornate>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_steel_reinforced>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_treated>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_treated_ornate>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:door_treated_reinforced>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:fencegate_aluminium>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:fencegate_steel>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:fencegate_treated>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:trapdoor_concrete>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:trapdoor_steel>);
mods.ItemStages.addItemStage("industrial", <engineersdoors:trapdoor_treated>);

mods.ItemStages.addItemStage("industrial", <minecraft:activator_rail>);
mods.ItemStages.addItemStage("industrial", <minecraft:comparator>);
mods.ItemStages.addItemStage("industrial", <minecraft:dispenser>);
mods.ItemStages.addItemStage("industrial", <minecraft:dropper>);
mods.ItemStages.addItemStage("industrial", <minecraft:gunpowder>);
mods.ItemStages.addItemStage("industrial", <minecraft:heavy_weighted_pressure_plate>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.fan>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.heater>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.hygro>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.plain>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.sieve>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.stabiliser>);
mods.ItemStages.addItemStage("industrial", <forestry:alveary.swarmer>);


mods.ItemStages.addItemStage("industrial", <ironchest:copper_iron_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:copper_iron_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:copper_silver_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:copper_silver_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:diamond_crystal_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:diamond_crystal_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:diamond_obsidian_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:diamond_obsidian_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:gold_diamond_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:gold_diamond_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_chest:7>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_gold_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_gold_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_black:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_blue:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_brown:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_cyan:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_gray:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_green:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_light_blue:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_lime:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_magenta:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_orange:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_pink:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_purple:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_red:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_silver:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_white:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow:1>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow:2>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow:3>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow:4>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow:5>);
mods.ItemStages.addItemStage("industrial", <ironchest:iron_shulker_box_yellow:6>);
mods.ItemStages.addItemStage("industrial", <ironchest:silver_gold_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:silver_gold_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:vanilla_copper_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:vanilla_iron_shulker_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:wood_copper_chest_upgrade>);
mods.ItemStages.addItemStage("industrial", <ironchest:wood_iron_chest_upgrade>);

mods.ItemStages.addItemStage("industrial", <minecraft:chest_minecart>);
mods.ItemStages.addItemStage("industrial", <minecraft:daylight_detector>);
mods.ItemStages.addItemStage("industrial", <minecraft:detector_rail>);
mods.ItemStages.addItemStage("industrial", <minecraft:fire_charge>);
mods.ItemStages.addItemStage("industrial", <minecraft:furnace_minecart>);
mods.ItemStages.addItemStage("industrial", <minecraft:hopper_minecart>);

mods.ItemStages.addItemStage("industrial", <ancientwarfarevehicle:ammo_cluster_shot_45> );
mods.ItemStages.addItemStage("industrial", <ancientwarfarevehicle:ammo_explosive_shot_10_big> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:block_dispenser> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:booster> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:buddy_block> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:corner_iron> );

mods.ItemStages.addItemStage("industrial", <betterwithmods:detector> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:detector_rail_steel> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:detector_rail_stone> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:dynamite> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:grate> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:grate:1> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:grate:2> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:grate:3> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:grate:4> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:grate:5> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:lens> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:light> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:material:18> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:material:19> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:material:28> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:material:29> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:mining_charge> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:moulding_iron> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:saw> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:siding_iron> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:slats> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:slats:1> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:slats:2> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:slats:3> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:slats:4> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:slats:5> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:stone_corner> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:stone_moulding> );
mods.ItemStages.addItemStage("industrial", <betterwithmods:stone_siding> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:atlasbook> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:atlasplate> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:bell> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:biblioclipboard> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:clock:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:handdrill> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:mapframe:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:maptool> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingcanvas> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeborderless:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframefancy:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframeflat:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframemiddle:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple:1> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple:2> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple:3> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple:4> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple:5> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingframesimple:6> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:paintingpress> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:printingpress> );
mods.ItemStages.addItemStage("industrial", <bibliocraft:printplate> );
mods.ItemStages.addItemStage("industrial", <conarm:travel_goggles> );
mods.ItemStages.addItemStage("industrial", <conarm:travel_night> );
mods.ItemStages.addItemStage("industrial", <creepingnether:hallowredstone> );
mods.ItemStages.addItemStage("industrial", <creepingnether:netherredstone> );
mods.ItemStages.addItemStage("industrial", <forestry:adventurer_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:adventurer_bag_t2> );
mods.ItemStages.addItemStage("industrial", <forestry:ambrosia> );
mods.ItemStages.addItemStage("industrial", <forestry:apatite> );
mods.ItemStages.addItemStage("industrial", <forestry:apiarist_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:apiarist_boots> );
mods.ItemStages.addItemStage("industrial", <forestry:apiarist_chest> );
mods.ItemStages.addItemStage("industrial", <forestry:apiarist_helmet> );
mods.ItemStages.addItemStage("industrial", <forestry:apiarist_legs> );
mods.ItemStages.addItemStage("industrial", <forestry:arboretum:1> );
mods.ItemStages.addItemStage("industrial", <forestry:beeswax> );
mods.ItemStages.addItemStage("industrial", <forestry:bituminous_peat> );
mods.ItemStages.addItemStage("industrial", <forestry:bog_earth> );
mods.ItemStages.addItemStage("industrial", <forestry:bottler> );
mods.ItemStages.addItemStage("industrial", <forestry:builder_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:builder_bag_t2> );
mods.ItemStages.addItemStage("industrial", <forestry:capsule> );
mods.ItemStages.addItemStage("industrial", <forestry:carpenter> );
mods.ItemStages.addItemStage("industrial", <forestry:centrifuge> );
mods.ItemStages.addItemStage("industrial", <forestry:crafting_material:1> );
mods.ItemStages.addItemStage("industrial", <forestry:crafting_material:2> );
mods.ItemStages.addItemStage("industrial", <forestry:crafting_material:3> );
mods.ItemStages.addItemStage("industrial", <forestry:crafting_material:6> );
mods.ItemStages.addItemStage("industrial", <forestry:decaying_wheat> );
mods.ItemStages.addItemStage("industrial", <forestry:digger_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:digger_bag_t2> );
mods.ItemStages.addItemStage("industrial", <forestry:engine_biogas> );
mods.ItemStages.addItemStage("industrial", <forestry:engine_clockwork> );
mods.ItemStages.addItemStage("industrial", <forestry:engine_peat> );
mods.ItemStages.addItemStage("industrial", <forestry:escritoire> );
mods.ItemStages.addItemStage("industrial", <forestry:farm_crops:1> );
mods.ItemStages.addItemStage("industrial", <forestry:farm_ender:1> );
mods.ItemStages.addItemStage("industrial", <forestry:farm_gourd:1> );
mods.ItemStages.addItemStage("industrial", <forestry:farm_mushroom:1> );
mods.ItemStages.addItemStage("industrial", <forestry:farm_nether:1> );
mods.ItemStages.addItemStage("industrial", <forestry:fertilizer_compound> );
mods.ItemStages.addItemStage("industrial", <forestry:forester_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:forester_bag_t2> );
mods.ItemStages.addItemStage("industrial", <forestry:frame_impregnated> );
mods.ItemStages.addItemStage("industrial", <forestry:frame_proven> );
mods.ItemStages.addItemStage("industrial", <forestry:frame_untreated> );
mods.ItemStages.addItemStage("industrial", <forestry:gear_bronze> );
mods.ItemStages.addItemStage("industrial", <forestry:gear_copper> );
mods.ItemStages.addItemStage("industrial", <forestry:gear_tin> );
mods.ItemStages.addItemStage("industrial", <forestry:honey_pot> );
mods.ItemStages.addItemStage("industrial", <forestry:honeydew> );
mods.ItemStages.addItemStage("industrial", <forestry:humus> );
mods.ItemStages.addItemStage("industrial", <forestry:hunter_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:hunter_bag_t2> );
mods.ItemStages.addItemStage("industrial", <forestry:impregnated_casing> );
mods.ItemStages.addItemStage("industrial", <forestry:lepidopterist_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:letters> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.0:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.0:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.0:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.1:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.1:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.1:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.2:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.2:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.2:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.3:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.3:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.3:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.4> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.4:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.4:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.4:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.5> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.5:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.5:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.5:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.6> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.6:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.6:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.6:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.fireproof.7> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.vanilla.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.vanilla.fireproof.0:1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.vanilla.fireproof.0:2> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.vanilla.fireproof.0:3> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.vanilla.fireproof.1> );
mods.ItemStages.addItemStage("industrial", <forestry:logs.vanilla.fireproof.1:1> );
mods.ItemStages.addItemStage("industrial", <forestry:miner_bag> );
mods.ItemStages.addItemStage("industrial", <forestry:miner_bag_t2> );
mods.ItemStages.addItemStage("industrial", <forestry:moistener> );
mods.ItemStages.addItemStage("industrial", <forestry:mouldy_wheat> );
mods.ItemStages.addItemStage("industrial", <forestry:mulch> );
mods.ItemStages.addItemStage("industrial", <forestry:naturalist_helmet> );
mods.ItemStages.addItemStage("industrial", <forestry:oak_stick> );
mods.ItemStages.addItemStage("industrial", <forestry:peat> );
mods.ItemStages.addItemStage("industrial", <forestry:peat_bog> );
mods.ItemStages.addItemStage("industrial", <forestry:peat_bog:1> );
mods.ItemStages.addItemStage("industrial", <forestry:phosphor> );
mods.ItemStages.addItemStage("industrial", <forestry:pipette> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:1> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:2> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:3> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:4> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:5> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:6> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:7> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:8> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:9> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:10> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:11> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:12> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:13> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:14> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.0:15> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:1> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:2> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:3> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:4> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:5> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:6> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:7> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:8> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:9> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:10> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:11> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.fireproof.1:12> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.vanilla.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.vanilla.fireproof.0:1> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.vanilla.fireproof.0:2> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.vanilla.fireproof.0:3> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.vanilla.fireproof.0:4> );
mods.ItemStages.addItemStage("industrial", <forestry:planks.vanilla.fireproof.0:5> );
mods.ItemStages.addItemStage("industrial", <forestry:propolis> );
mods.ItemStages.addItemStage("industrial", <forestry:propolis:1> );
mods.ItemStages.addItemStage("industrial", <forestry:propolis:3> );
mods.ItemStages.addItemStage("industrial", <forestry:refractory> );
mods.ItemStages.addItemStage("industrial", <forestry:refractory_wax> );
mods.ItemStages.addItemStage("industrial", <forestry:research_note> );
mods.ItemStages.addItemStage("industrial", <forestry:resource_storage> );
mods.ItemStages.addItemStage("industrial", <forestry:resource_storage:1> );
mods.ItemStages.addItemStage("industrial", <forestry:resource_storage:2> );
mods.ItemStages.addItemStage("industrial", <forestry:resource_storage:3> );
mods.ItemStages.addItemStage("industrial", <forestry:resources> );
mods.ItemStages.addItemStage("industrial", <forestry:resources:1> );
mods.ItemStages.addItemStage("industrial", <forestry:resources:2> );
mods.ItemStages.addItemStage("industrial", <forestry:royal_jelly> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.double.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.double.fireproof.1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.double.fireproof.2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.double.fireproof.3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:4> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:5> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:6> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.0:7> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:4> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:5> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:6> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.1:7> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:4> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:5> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:6> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.2:7> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.3:1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.3:2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.3:3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.fireproof.3:4> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.double.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.fireproof.0> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.fireproof.0:1> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.fireproof.0:2> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.fireproof.0:3> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.fireproof.0:4> );
mods.ItemStages.addItemStage("industrial", <forestry:slabs.vanilla.fireproof.0:5> );
mods.ItemStages.addItemStage("industrial", <forestry:squeezer> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.acacia> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.balsa> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.baobab> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.cherry> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.chestnut> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.citrus> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.cocobolo> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.ebony> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.giganteum> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.greenheart> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.ipe> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.kapok> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.larch> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.lime> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.mahoe> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.mahogany> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.maple> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.padauk> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.palm> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.papaya> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.pine> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.plum> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.poplar> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.sequoia> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.teak> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.walnut> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.wenge> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.willow> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.fireproof.zebrawood> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.vanilla.fireproof.acacia> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.vanilla.fireproof.birch> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.vanilla.fireproof.dark_oak> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.vanilla.fireproof.jungle> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.vanilla.fireproof.oak> );
mods.ItemStages.addItemStage("industrial", <forestry:stairs.vanilla.fireproof.spruce> );
mods.ItemStages.addItemStage("industrial", <forestry:sturdy_machine> );
mods.ItemStages.addItemStage("industrial", <forestry:tree_chest> );
mods.ItemStages.addItemStage("industrial", <forestry:wrench> );
mods.ItemStages.addItemStage("industrial", <grapplemod:doublemotorhook> );
mods.ItemStages.addItemStage("industrial", <grapplemod:forcefieldupgradeitem> );
mods.ItemStages.addItemStage("industrial", <grapplemod:magnethook> );
mods.ItemStages.addItemStage("industrial", <grapplemod:magnetupgradeitem> );
mods.ItemStages.addItemStage("industrial", <grapplemod:motorhook> );
mods.ItemStages.addItemStage("industrial", <grapplemod:motorupgradeitem> );
mods.ItemStages.addItemStage("industrial", <grapplemod:staffupgradeitem> );
mods.ItemStages.addItemStage("industrial", <harvestcraft:grinder> );
mods.ItemStages.addItemStage("industrial", <infoaccessories:info_accessory:6> );
mods.ItemStages.addItemStage("industrial", <malisisdoors:factory_door> );
mods.ItemStages.addItemStage("industrial", <malisisdoors:verticalhatch> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:acacia_rail_bridge> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:acacia_rail_bridge_end> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:birch_rail_bridge> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:birch_rail_bridge_end> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:dark_oak_rail_bridge> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:dark_oak_rail_bridge_end> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:jungle_rail_bridge> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:jungle_rail_bridge_end> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:oak_rail_bridge> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:oak_rail_bridge_end> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:spruce_rail_bridge> );
mods.ItemStages.addItemStage("industrial", <mcwbridges:spruce_rail_bridge_end> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:1> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:2> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:3> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:4> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:5> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:6> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:7> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:8> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:9> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:10> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:11> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:12> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:13> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:14> );
mods.ItemStages.addItemStage("industrial", <mekanism:balloon:15> );
mods.ItemStages.addItemStage("industrial", <mekanism:basicblock:13> );
mods.ItemStages.addItemStage("industrial", <mekanism:nugget:6> );
mods.ItemStages.addItemStage("industrial", <minecraft:activator_rail> );
mods.ItemStages.addItemStage("industrial", <minecraft:black_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:blue_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:brown_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:chest_minecart> );
mods.ItemStages.addItemStage("industrial", <minecraft:chorus_flower> );
mods.ItemStages.addItemStage("industrial", <minecraft:chorus_fruit> );
mods.ItemStages.addItemStage("industrial", <minecraft:chorus_fruit_popped> );
mods.ItemStages.addItemStage("industrial", <minecraft:chorus_plant> );
mods.ItemStages.addItemStage("industrial", <minecraft:clock> );
mods.ItemStages.addItemStage("industrial", <minecraft:coal> );
mods.ItemStages.addItemStage("industrial", <minecraft:coal:1> );
mods.ItemStages.addItemStage("industrial", <minecraft:coal_block> );
mods.ItemStages.addItemStage("industrial", <minecraft:coal_ore> );
mods.ItemStages.addItemStage("industrial", <minecraft:comparator> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:1> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:2> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:3> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:4> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:5> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:6> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:7> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:8> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:9> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:10> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:11> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:12> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:13> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:14> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete:15> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:1> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:2> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:3> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:4> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:5> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:6> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:7> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:8> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:9> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:10> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:11> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:12> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:13> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:14> );
mods.ItemStages.addItemStage("industrial", <minecraft:concrete_powder:15> );
mods.ItemStages.addItemStage("industrial", <minecraft:cyan_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:daylight_detector> );
mods.ItemStages.addItemStage("industrial", <minecraft:detector_rail> );
mods.ItemStages.addItemStage("industrial", <minecraft:dispenser> );
mods.ItemStages.addItemStage("industrial", <minecraft:dragon_breath> );
mods.ItemStages.addItemStage("industrial", <minecraft:dragon_egg> );
mods.ItemStages.addItemStage("industrial", <minecraft:dropper> );
mods.ItemStages.addItemStage("industrial", <minecraft:end_bricks> );
mods.ItemStages.addItemStage("industrial", <minecraft:end_crystal> );
mods.ItemStages.addItemStage("industrial", <minecraft:end_portal_frame> );
mods.ItemStages.addItemStage("industrial", <minecraft:end_rod> );
mods.ItemStages.addItemStage("industrial", <minecraft:ender_chest> );
mods.ItemStages.addItemStage("industrial", <minecraft:fire_charge> );
mods.ItemStages.addItemStage("industrial", <minecraft:firework_charge> );
mods.ItemStages.addItemStage("industrial", <minecraft:fireworks> );
mods.ItemStages.addItemStage("industrial", <minecraft:furnace_minecart> );
mods.ItemStages.addItemStage("industrial", <minecraft:golden_rail> );
mods.ItemStages.addItemStage("industrial", <minecraft:gray_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:green_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:gunpowder> );
mods.ItemStages.addItemStage("industrial", <minecraft:heavy_weighted_pressure_plate> );
mods.ItemStages.addItemStage("industrial", <minecraft:hopper> );
mods.ItemStages.addItemStage("industrial", <minecraft:hopper_minecart> );
mods.ItemStages.addItemStage("industrial", <minecraft:iron_bars> );
mods.ItemStages.addItemStage("industrial", <minecraft:lever> );
mods.ItemStages.addItemStage("industrial", <minecraft:light_blue_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:light_weighted_pressure_plate> );
mods.ItemStages.addItemStage("industrial", <minecraft:lime_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:magenta_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:minecart> );
mods.ItemStages.addItemStage("industrial", <minecraft:observer> );
mods.ItemStages.addItemStage("industrial", <minecraft:orange_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:pink_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:piston> );
mods.ItemStages.addItemStage("industrial", <minecraft:purple_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:purpur_block> );
mods.ItemStages.addItemStage("industrial", <minecraft:purpur_pillar> );
mods.ItemStages.addItemStage("industrial", <minecraft:purpur_slab> );
mods.ItemStages.addItemStage("industrial", <minecraft:purpur_stairs> );
mods.ItemStages.addItemStage("industrial", <minecraft:rail> );
mods.ItemStages.addItemStage("industrial", <minecraft:red_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:redstone> );
mods.ItemStages.addItemStage("industrial", <minecraft:redstone_block> );
mods.ItemStages.addItemStage("industrial", <minecraft:redstone_lamp> );
mods.ItemStages.addItemStage("industrial", <minecraft:redstone_ore> );
mods.ItemStages.addItemStage("industrial", <minecraft:redstone_torch> );
mods.ItemStages.addItemStage("industrial", <minecraft:repeater> );
mods.ItemStages.addItemStage("industrial", <minecraft:shulker_shell> );
mods.ItemStages.addItemStage("industrial", <minecraft:silver_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:sticky_piston> );
mods.ItemStages.addItemStage("industrial", <minecraft:stone_button> );
mods.ItemStages.addItemStage("industrial", <minecraft:stone_pressure_plate> );
mods.ItemStages.addItemStage("industrial", <minecraft:tnt> );
mods.ItemStages.addItemStage("industrial", <minecraft:tnt_minecart> );
mods.ItemStages.addItemStage("industrial", <minecraft:white_shulker_box> );
mods.ItemStages.addItemStage("industrial", <minecraft:wooden_pressure_plate> );
mods.ItemStages.addItemStage("industrial", <minecraft:yellow_shulker_box> );
mods.ItemStages.addItemStage("industrial", <primal:zinc_dust> );
mods.ItemStages.addItemStage("industrial", <primal:zinc_ingot> );
mods.ItemStages.addItemStage("industrial", <primal:zinc_nugget> );
mods.ItemStages.addItemStage("industrial", <primal:zinc_plate> );
mods.ItemStages.addItemStage("industrial", <quark:archaeologist_hat> );
mods.ItemStages.addItemStage("industrial", <quark:redstone_inductor> );
mods.ItemStages.addItemStage("industrial", <quark:redstone_randomizer> );
mods.ItemStages.addItemStage("industrial", <roots:wildwood_button> );
mods.ItemStages.addItemStage("industrial", <roots:wildwood_pressure_plate> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:chandelier_brass> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_aer> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_alienis> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_alkimia> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_aqua> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_auram> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_aversio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_bestia> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_aer> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_alienis> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_alkimia> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_aqua> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_auram> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_aversio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_bestia> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_cognitio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_desiderium> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_exanimis> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_fabrico> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_gelum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_herba> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_humanus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_ignis> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_instrumentum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_lux> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_machina> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_metallum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_mortuus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_motus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_ordo> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_perditio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_permutatio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_potentia> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_praecantatio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_praemunio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_sensus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_spiritus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_tenebrae> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_terra> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_vacuos> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_victus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_vinculum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_vitium> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_vitreus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_brass_volatus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_cognitio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_desiderium> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_exanimis> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_fabrico> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_gelum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_herba> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_humanus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_ignis> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_instrumentum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_lux> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_machina> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_metallum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_mortuus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_motus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_ordo> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_perditio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_permutatio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_potentia> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_praecantatio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_praemunio> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_sensus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_spiritus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_tenebrae> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_terra> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_vacuos> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_victus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_vinculum> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_vitium> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_vitreus> );
mods.ItemStages.addItemStage("industrial", <rusticthaumaturgy:sconce_volatus> );
mods.ItemStages.addItemStage("industrial", <slabmachines:tnt_slab> );
mods.ItemStages.addItemStage("industrial", <storagedrawers:upgrade_redstone> );
mods.ItemStages.addItemStage("industrial", <storagedrawers:upgrade_redstone:1> );
mods.ItemStages.addItemStage("industrial", <storagedrawers:upgrade_redstone:2> );
mods.ItemStages.addItemStage("industrial", <tconstruct:materials:12> );
mods.ItemStages.addItemStage("industrial", <tconstruct:materials:13> );
mods.ItemStages.addItemStage("industrial", <tconstruct:wood_rail> );
mods.ItemStages.addItemStage("industrial", <tconstruct:wood_rail_trapdoor> );
mods.ItemStages.addItemStage("industrial", <telepastries:end_cake> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:base_addon> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:energy_tier1> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:energy_tier2> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:gear_diamond> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:gear_gold> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:gear_stone> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:machine_case> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:speed_tier1> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:speed_tier2> );
mods.ItemStages.addItemStage("industrial", <teslacorelib:wrench> );