import crafttweaker.item.IIngredient;


mods.WailaStages.addWailaStage("medieval");

mods.ItemStages.stageRecipeCategory("medieval", "minecraft.anvil");
mods.ItemStages.stageRecipeCategory("medieval", "minecraft.furnace");
mods.ItemStages.stageRecipeCategory("medieval", "minecraft.crafting_table");
mods.ItemStages.stageRecipeCategory("medieval", "minecraft.crafting_table");

mods.ItemStages.stageModItems("medieval","bewitchment");
mods.ItemStages.stageModItems("medieval","endercrop");
mods.ItemStages.stageModItems("medieval","multibeds");
mods.ItemStages.stageModItems("medieval","rusticbopwoods");
mods.ItemStages.stageModItems("medieval","rusticwitchcraft");
mods.ItemStages.stageModItems("medieval","tfspellpack");
mods.ItemStages.stageModItems("medieval","waystones");
mods.ItemStages.stageModItems("medieval","wizardryutils");


var medievalIngredients as IIngredient[] = [
    <minecraft:furnace>,
    <bibliocraft:armorstand>,
    <bibliocraft:armorstand:1>,
    <bibliocraft:armorstand:2>,
    <bibliocraft:armorstand:3>,
    <bibliocraft:armorstand:4>,
    <bibliocraft:armorstand:5>,
    <bibliocraft:armorstand:6>,
    <bibliocraft:atlasbook>,
    <bibliocraft:atlasplate>,
    <bibliocraft:bell>,
    <bibliocraft:bibliochase>,
    <bibliocraft:biblioclipboard>,
    <bibliocraft:bibliocreativelock>,
    <bibliocraft:bibliodrill>,
    <bibliocraft:biblioglasses>,
    <bibliocraft:biblioredbook>,
    <bibliocraft:bigbook>,
    <bibliocraft:bookcase>,
    <bibliocraft:bookcase:1>,
    <bibliocraft:bookcase:2>,
    <bibliocraft:bookcase:3>,
    <bibliocraft:bookcase:4>,
    <bibliocraft:bookcase:5>,
    <bibliocraft:bookcase:6>,
    <bibliocraft:bookcasecreative>,
    <bibliocraft:bookcasecreative:1>,
    <bibliocraft:bookcasecreative:2>,
    <bibliocraft:bookcasecreative:3>,
    <bibliocraft:bookcasecreative:4>,
    <bibliocraft:bookcasecreative:5>,
    <bibliocraft:bookcasecreative:6>,
    <forestry:worktable>,
    <primal:worktable_shelf>.withTag({type: "oak"}),
    <primal:worktable_shelf:1>.withTag({type: "spruce"}),
    <primal:worktable_shelf:2>.withTag({type: "birch"}),
    <primal:worktable_shelf:3>.withTag({type: "jungle"}),
    <primal:worktable_shelf:4>.withTag({type: "acacia"}),
    <primal:worktable_shelf:5>.withTag({type: "dark_oak"}),
    <primal:worktable_shelf:6>.withTag({type: "ironwood"}),
    <primal:worktable_shelf:7>.withTag({type: "yew"}),
    <primal:worktable_shelf:8>.withTag({type: "lacquer"}),
    <primal:worktable_shelf:9>.withTag({type: "corypha"}),
    <primal:worktable_slab>.withTag({type: "oak"}),
    <primal:worktable_slab:1>.withTag({type: "spruce"}),
    <primal:worktable_slab:2>.withTag({type: "birch"}),
    <primal:worktable_slab:3>.withTag({type: "jungle"}),
    <primal:worktable_slab:4>.withTag({type: "acacia"}),
    <primal:worktable_slab:5>.withTag({type: "dark_oak"}),
    <primal:worktable_slab:6>.withTag({type: "ironwood"}),
    <primal:worktable_slab:7>.withTag({type: "yew"}),
    <primal:worktable_slab:8>.withTag({type: "lacquer"}),
    <primal:worktable_slab:9>.withTag({type: "corypha"}),
    <bibliocraft:case>,
    <bibliocraft:case:1>,
    <bibliocraft:case:2>,
    <bibliocraft:case:3>,
    <bibliocraft:case:4>,
    <bibliocraft:case:5>,
    <bibliocraft:case:6>,
    <bibliocraft:clipboard>,
    <bibliocraft:clock>,
    <bibliocraft:clock:1>,
    <bibliocraft:clock:2>,
    <bibliocraft:clock:3>,
    <bibliocraft:clock:4>,
    <bibliocraft:clock:5>,
    <bibliocraft:clock:6>,
    <bibliocraft:compass>,
    <bibliocraft:deathcompass>,
    <bibliocraft:desk>,
    <bibliocraft:desk:1>,
    <bibliocraft:desk:2>,
    <bibliocraft:desk:3>,
    <bibliocraft:desk:4>,
    <bibliocraft:desk:5>,
    <bibliocraft:desk:6>,
    <bibliocraft:fancysign>,
    <bibliocraft:fancysign:1>,
    <bibliocraft:fancysign:2>,
    <bibliocraft:fancysign:3>,
    <bibliocraft:fancysign:4>,
    <bibliocraft:fancysign:5>,
    <bibliocraft:fancysign:6>,
    <bibliocraft:fancyworkbench>,
    <bibliocraft:fancyworkbench:1>,
    <bibliocraft:fancyworkbench:2>,
    <bibliocraft:fancyworkbench:3>,
    <bibliocraft:fancyworkbench:4>,
    <bibliocraft:fancyworkbench:5>,
    <bibliocraft:fancyworkbench:6>,
    <bibliocraft:framedchest>,
    <bibliocraft:framedchest:1>,
    <bibliocraft:framedchest:2>,
    <bibliocraft:framedchest:3>,
    <bibliocraft:framedchest:4>,
    <bibliocraft:framedchest:5>,
    <bibliocraft:framedchest:6>,
    <bibliocraft:framingboard>,
    <bibliocraft:framingsaw>,
    <bibliocraft:framingsheet>,
    <bibliocraft:furniturepaneler>,
    <bibliocraft:furniturepaneler:1>,
    <bibliocraft:furniturepaneler:2>,
    <bibliocraft:furniturepaneler:3>,
    <bibliocraft:furniturepaneler:4>,
    <bibliocraft:furniturepaneler:5>,
    <bibliocraft:furniturepaneler:6>,
    <bibliocraft:label>,
    <bibliocraft:label:1>,
    <bibliocraft:label:2>,
    <bibliocraft:label:3>,
    <bibliocraft:label:4>,
    <bibliocraft:label:5>,
    <bibliocraft:label:6>,
    <bibliocraft:lampgold>,
    <bibliocraft:lampgold:1>,
    <bibliocraft:lampgold:2>,
    <bibliocraft:lampgold:3>,
    <bibliocraft:lampgold:4>,
    <bibliocraft:lampgold:5>,
    <bibliocraft:lampgold:6>,
    <bibliocraft:lampgold:7>,
    <bibliocraft:lampgold:8>,
    <bibliocraft:lampgold:9>,
    <bibliocraft:lampgold:10>,
    <bibliocraft:lampgold:11>,
    <bibliocraft:lampgold:12>,
    <bibliocraft:lampgold:13>,
    <bibliocraft:lampgold:14>,
    <bibliocraft:lampgold:15>,
    <bibliocraft:lampiron>,
    <bibliocraft:lampiron:1>,
    <bibliocraft:lampiron:2>,
    <bibliocraft:lampiron:3>,
    <bibliocraft:lampiron:4>,
    <bibliocraft:lampiron:5>,
    <bibliocraft:lampiron:6>,
    <bibliocraft:lampiron:7>,
    <bibliocraft:lampiron:8>,
    <bibliocraft:lampiron:9>,
    <bibliocraft:lampiron:10>,
    <bibliocraft:lampiron:11>,
    <bibliocraft:lampiron:12>,
    <bibliocraft:lampiron:13>,
    <bibliocraft:lampiron:14>,
    <bibliocraft:lampiron:15>,
    <bibliocraft:lanterngold>,
    <bibliocraft:lanterngold:1>,
    <bibliocraft:lanterngold:2>,
    <bibliocraft:lanterngold:3>,
    <bibliocraft:lanterngold:4>,
    <bibliocraft:lanterngold:5>,
    <bibliocraft:lanterngold:6>,
    <bibliocraft:lanterngold:7>,
    <bibliocraft:lanterngold:8>,
    <bibliocraft:lanterngold:9>,
    <bibliocraft:lanterngold:10>,
    <bibliocraft:lanterngold:11>,
    <bibliocraft:lanterngold:12>,
    <bibliocraft:lanterngold:13>,
    <bibliocraft:lanterngold:14>,
    <bibliocraft:lanterngold:15>,
    <bibliocraft:lanterniron>,
    <bibliocraft:lanterniron:1>,
    <bibliocraft:lanterniron:2>,
    <bibliocraft:lanterniron:3>,
    <bibliocraft:lanterniron:4>,
    <bibliocraft:lanterniron:5>,
    <bibliocraft:lanterniron:6>,
    <bibliocraft:lanterniron:7>,
    <bibliocraft:lanterniron:8>,
    <bibliocraft:lanterniron:9>,
    <bibliocraft:lanterniron:10>,
    <bibliocraft:lanterniron:11>,
    <bibliocraft:lanterniron:12>,
    <bibliocraft:lanterniron:13>,
    <bibliocraft:lanterniron:14>,
    <bibliocraft:lanterniron:15>,
    <bibliocraft:mapframe>,
    <bibliocraft:mapframe:1>,
    <bibliocraft:mapframe:2>,
    <bibliocraft:mapframe:3>,
    <bibliocraft:mapframe:4>,
    <bibliocraft:mapframe:5>,
    <bibliocraft:mapframe:6>,
    <bibliocraft:maptool>,
    <bibliocraft:markerpole>,
    <bibliocraft:paintingcanvas>,
    <bibliocraft:paintingframeborderless>,
    <bibliocraft:paintingframeborderless:1>,
    <bibliocraft:paintingframeborderless:2>,
    <bibliocraft:paintingframeborderless:3>,
    <bibliocraft:paintingframeborderless:4>,
    <bibliocraft:paintingframeborderless:5>,
    <bibliocraft:paintingframeborderless:6>,
    <bibliocraft:paintingframefancy>,
    <bibliocraft:paintingframefancy:1>,
    <bibliocraft:paintingframefancy:2>,
    <bibliocraft:paintingframefancy:3>,
    <bibliocraft:paintingframefancy:4>,
    <bibliocraft:paintingframefancy:5>,
    <bibliocraft:paintingframefancy:6>,
    <bibliocraft:paintingframeflat>,
    <bibliocraft:paintingframeflat:1>,
    <bibliocraft:paintingframeflat:2>,
    <bibliocraft:paintingframeflat:3>,
    <bibliocraft:paintingframeflat:4>,
    <bibliocraft:paintingframeflat:5>,
    <bibliocraft:paintingframeflat:6>,
    <bibliocraft:paintingframemiddle>,
    <bibliocraft:paintingframemiddle:1>,
    <bibliocraft:paintingframemiddle:2>,
    <bibliocraft:paintingframemiddle:3>,
    <bibliocraft:paintingframemiddle:4>,
    <bibliocraft:paintingframemiddle:5>,
    <bibliocraft:paintingframemiddle:6>,
    <bibliocraft:paintingframesimple>,
    <bibliocraft:paintingframesimple:1>,
    <bibliocraft:paintingframesimple:2>,
    <bibliocraft:paintingframesimple:3>,
    <bibliocraft:paintingframesimple:4>,
    <bibliocraft:paintingframesimple:5>,
    <bibliocraft:paintingframesimple:6>,
    <bibliocraft:paintingpress>,
    <bibliocraft:potionshelf>,
    <bibliocraft:potionshelf:1>,
    <bibliocraft:potionshelf:2>,
    <bibliocraft:potionshelf:3>,
    <bibliocraft:potionshelf:4>,
    <bibliocraft:potionshelf:5>,
    <bibliocraft:potionshelf:6>,
    <bibliocraft:recipebook>,
    <bibliocraft:seat>,
    <bibliocraft:seat:1>,
    <bibliocraft:seat:2>,
    <bibliocraft:seat:3>,
    <bibliocraft:seat:4>,
    <bibliocraft:seat:5>,
    <bibliocraft:seat:6>,
    <bibliocraft:seatback1>,
    <bibliocraft:seatback2>,
    <bibliocraft:seatback3>,
    <bibliocraft:seatback4>,
    <bibliocraft:seatback5>,
    <bibliocraft:shelf>,
    <bibliocraft:shelf:1>,
    <bibliocraft:shelf:2>,
    <bibliocraft:shelf:3>,
    <bibliocraft:shelf:4>,
    <bibliocraft:shelf:5>,
    <bibliocraft:shelf:6>,
    <bibliocraft:slottedbook>,
    <bibliocraft:stockroomcatalog>,
    <bibliocraft:swordpedestal>,
    <bibliocraft:swordpedestal:1>,
    <bibliocraft:swordpedestal:2>,
    <bibliocraft:swordpedestal:3>,
    <bibliocraft:swordpedestal:4>,
    <bibliocraft:swordpedestal:5>,
    <bibliocraft:swordpedestal:6>,
    <bibliocraft:swordpedestal:7>,
    <bibliocraft:swordpedestal:8>,
    <bibliocraft:swordpedestal:9>,
    <bibliocraft:swordpedestal:10>,
    <bibliocraft:swordpedestal:11>,
    <bibliocraft:swordpedestal:12>,
    <bibliocraft:swordpedestal:13>,
    <bibliocraft:swordpedestal:14>,
    <bibliocraft:swordpedestal:15>,
    <bibliocraft:table>,
    <bibliocraft:table:1>,
    <bibliocraft:table:2>,
    <bibliocraft:table:3>,
    <bibliocraft:table:4>,
    <bibliocraft:table:5>,
    <bibliocraft:table:6>,
    <bibliocraft:testeritem>,
    <bibliocraft:toolrack>,
    <bibliocraft:toolrack:1>,
    <bibliocraft:toolrack:2>,
    <bibliocraft:toolrack:3>,
    <bibliocraft:toolrack:4>,
    <bibliocraft:toolrack:5>,
    <bibliocraft:toolrack:6>,
    <biomesoplenty:boat_cherry>,
    <biomesoplenty:boat_ebony>,
    <biomesoplenty:boat_ethereal>,
    <biomesoplenty:boat_eucalyptus>,
    <biomesoplenty:boat_fir>,
    <biomesoplenty:boat_hellbark>,
    <biomesoplenty:boat_jacaranda>,
    <biomesoplenty:boat_magic>,
    <biomesoplenty:boat_mahogany>,
    <biomesoplenty:boat_mangrove>,
    <biomesoplenty:boat_palm>,
    <biomesoplenty:boat_pine>,
    <biomesoplenty:boat_redwood>,
    <biomesoplenty:boat_sacred_oak>,
    <biomesoplenty:boat_umbran>,
    <biomesoplenty:boat_willow>,
    <biomesoplenty:sacred_oak_door>,
    <biomesoplenty:cherry_door>,
    <biomesoplenty:umbran_door>,
    <biomesoplenty:fir_door>,
    <biomesoplenty:magic_door>,
    <biomesoplenty:mangrove_door>,
    <biomesoplenty:palm_door>,
    <biomesoplenty:redwood_door>,
    <biomesoplenty:willow_door>,
    <biomesoplenty:pine_door>,
    <biomesoplenty:hellbark_door>,
    <biomesoplenty:jacaranda_door>,
    <biomesoplenty:mahogany_door>,
    <biomesoplenty:ebony_door>,
    <biomesoplenty:eucalyptus_door>,
    <biomesoplenty:ethereal_door>,
    <biomesoplenty:bramble_plant>,
    <biomesoplenty:brown_dye>,
    <conarm:frosty_soles>,
    <conarm:gauntlet_mat>,
    <conarm:gauntlet_mat_attack>,
    <conarm:gauntlet_mat_reach>,
    <conarm:gauntlet_mat_speed>,
    <conarm:invisible_ink>,
    <conarm:resist_mat>,
    <conarm:resist_mat_blast>,
    <conarm:resist_mat_fire>,
    <conarm:resist_mat_proj>,
    <conarm:travel_belt>,
    <conarm:travel_belt_base>,
    <conarm:travel_cloak>,
    <conarm:travel_potion>,
    <conarm:travel_sack>,
    <conarm:travel_slowfall>,
    <conarm:travel_sneak>,
    <conarm:travel_soul>,
    <cookingforblockheads:cabinet>,
    <cookingforblockheads:cooking_table>,
    <cookingforblockheads:corner>,
    <cookingforblockheads:counter>,
    <cookingforblockheads:cutting_board>,
    <cookingforblockheads:fruit_basket>,
    <cookingforblockheads:recipe_book>,
    <cookingforblockheads:recipe_book:1>,
    <cookingforblockheads:recipe_book:2>,
    <cookingforblockheads:spice_rack>,
//    <cookingforblockheads:tool_rack>,
    <culinaryconstruct:sandwich_station>,


    <improvedbackpacks:upgrade:2>,
    <improvedbackpacks:upgrade:3>,
    <improvedbackpacks:upgrade:4>,

    <pirates:cell>,

    <minecraft:banner:15>,
    <minecraft:banner:14>,
    <minecraft:banner:13>,
    <minecraft:banner:12>,
    <minecraft:banner:11>,
    <minecraft:banner:10>,
    <minecraft:banner:9>,
    <minecraft:banner:8>,
    <minecraft:banner:7>,
    <minecraft:banner:6>,
    <minecraft:banner:5>,
    <minecraft:banner:4>,
    <minecraft:banner:3>,
    <minecraft:banner:2>,
    <minecraft:banner:1>,
    <minecraft:banner>,
    <minecraft:brewing_stand>,
    <minecraft:carpet>,
    <minecraft:carpet:1>,
    <minecraft:carpet:2>,
    <minecraft:carpet:3>,
    <minecraft:carpet:4>,
    <minecraft:carpet:5>,
    <minecraft:carpet:6>,
    <minecraft:carpet:7>,
    <minecraft:carpet:8>,
    <minecraft:carpet:9>,
    <minecraft:carpet:10>,
    <minecraft:carpet:11>,
    <minecraft:carpet:12>,
    <minecraft:carpet:13>,
    <minecraft:carpet:14>,
    <minecraft:carpet:15>,
    <minecraft:clock>,
    <minecraft:enchanting_table>,


    <minecraft:chainmail_boots>,
    <minecraft:chainmail_chestplate>,
    <minecraft:chainmail_helmet>,
    <minecraft:chainmail_leggings>,

    <ancientwarfareautomation:worksite_upgrade:6>,
    <ancientwarfarenpc:bard_instrument>,
    <ancientwarfarenpc:iron_cleaver>,
    <ancientwarfarenpc:iron_command_baton>,
    <ancientwarfarenpc:iron_halberd>,
    <ancientwarfarenpc:iron_lance>,
    <ancientwarfarenpc:iron_shield>,
    <ancientwarfarenpc:gold_shield>,
    <ancientwarfarenpc:diamond_shield>,
    <ancientwarfarenpc:shield_witchbane_1>,
    <ancientwarfarenpc:shield_witchbane_2>,
    <ancientwarfarenpc:sickle>,
    <ancientwarfarestructure:altar_lectern>,
    <ancientwarfarestructure:chair>.withTag({variant: "oak"}),
    <ancientwarfarestructure:coin_stack_gold>.withTag({size: 8}),
    <ancientwarfarestructure:coin_stack_silver>.withTag({size: 8}),
    <ancientwarfarestructure:construction_tool>,
    <ancientwarfarestructure:construction_tool_lakes>,
    <ancientwarfarestructure:decorative_flag>.withTag({name: "rakshasa"}),
    <ancientwarfarestructure:drafting_station>,
    <ancientwarfarestructure:gate_spawner>,
    <ancientwarfarestructure:gate_spawner:4>,
    <ancientwarfarestructure:gate_spawner:5>,
    <ancientwarfarestructure:scissor_seat>,
    <ancientwarfarestructure:spawner_placer>,
    <ancientwarfarestructure:statue>,
    <ancientwarfarestructure:table>.withTag({variant: "oak"}),
    <ancientwarfarestructure:tribal_chair>,
    <ancientwarfarestructure:tribal_stool>,
    <ancientwarfarestructure:urn>,
    <ancientwarfarestructure:wooden_coffin>.withTag({variant: "oak"}),
    <ancientwarfarestructure:wooden_post>,
    <ancientwarfarestructure:wooden_throne>,
    <ancientwarfarevehicle:ammo_ballista_bolt_explosive>,
    <ancientwarfarevehicle:ammo_ballista_bolt_flame>,
    <ancientwarfarevehicle:ammo_ballista_bolt_iron>,
    <ancientwarfarevehicle:ammo_explosive_shot_15>,
    <ancientwarfarevehicle:ammo_explosive_shot_30_big>,
    <ancientwarfarevehicle:ammo_hwacha_rocket>,
    <ancientwarfarevehicle:ammo_hwacha_rocket_airburst>,
    <ancientwarfarevehicle:iron_core_wood>,
    <ancientwarfarevehicle:ironshod_wood>,
    <ancientwarfarevehicle:spawner:2>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:5>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:8>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:9>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:10>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:11>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:12>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:13>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:14>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:18>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:spawner:19>.withTag({spawnData: {level: 0}}),
    <ancientwarfarevehicle:treated_wood>,
    <animania:block_hamster_wheel>,
//    <apotheosis:farmers_leash>,
    <betterwithmods:bellows>,
    <betterwithmods:bellows:1>,
    <betterwithmods:infernal_enchanter>,
    <betterwithmods:iron_wall>,
    <betterwithmods:material>,
    <betterwithmods:material:4>,
    <betterwithmods:material:8>,
    <betterwithmods:material:9>,
    <betterwithmods:material:10>,
    <betterwithmods:material:11>,
    <betterwithmods:material:14>,
    <betterwithmods:material:30>,
    <betterwithmods:material:41>,
    <betterwithmods:material:48>,
    <betterwithmods:material:49>,
    <betterwithmods:material:51>,
    <betterwithmods:screw_pump>,
    <betterwithmods:single_machine>,
    <betterwithmods:steel_axle>,
    <betterwithmods:steel_block>,
    <betterwithmods:steel_broken_gearbox>,
    <betterwithmods:steel_gearbox>,
    <betterwithmods:steel_pressure_plate>,
    <betterwithmods:wooden_axle>,
    <betterwithmods:wooden_broken_gearbox>,
    <betterwithmods:wooden_gearbox>,
    <bibliocraft:compass>,
    <bibliocraft:fancyworkbench>,
    <bibliocraft:fancyworkbench:1>,
    <bibliocraft:fancyworkbench:2>,
    <bibliocraft:fancyworkbench:3>,
    <bibliocraft:fancyworkbench:4>,
    <bibliocraft:fancyworkbench:5>,
    <bibliocraft:fancyworkbench:6>,
    <bibliocraft:framedchest>,
    <bibliocraft:framedchest:1>,
    <bibliocraft:framedchest:2>,
    <bibliocraft:framedchest:3>,
    <bibliocraft:framedchest:4>,
    <bibliocraft:framedchest:5>,
    <bibliocraft:framedchest:6>,
    <bibliocraft:potionshelf>,
    <bibliocraft:potionshelf:1>,
    <bibliocraft:potionshelf:2>,
    <bibliocraft:potionshelf:3>,
    <bibliocraft:potionshelf:4>,
    <bibliocraft:potionshelf:5>,
    <bibliocraft:potionshelf:6>,
    <bibliocraft:recipebook>,
    <bibliocraft:seat>,
    <bibliocraft:seat:1>,
    <bibliocraft:seat:2>,
    <bibliocraft:seat:3>,
    <bibliocraft:seat:4>,
    <bibliocraft:seat:5>,
    <bibliocraft:seat:6>,
    <bibliocraft:seatback1>,
    <bibliocraft:seatback2>,
    <bibliocraft:seatback3>,
    <bibliocraft:seatback4>,
    <bibliocraft:seatback5>,
    <bibliocraft:swordpedestal>,
    <bibliocraft:swordpedestal:1>,
    <bibliocraft:swordpedestal:2>,
    <bibliocraft:swordpedestal:3>,
    <bibliocraft:swordpedestal:4>,
    <bibliocraft:swordpedestal:5>,
    <bibliocraft:swordpedestal:6>,
    <bibliocraft:swordpedestal:7>,
    <bibliocraft:swordpedestal:8>,
    <bibliocraft:swordpedestal:9>,
    <bibliocraft:swordpedestal:10>,
    <bibliocraft:swordpedestal:11>,
    <bibliocraft:swordpedestal:12>,
    <bibliocraft:swordpedestal:13>,
    <bibliocraft:swordpedestal:14>,
    <bibliocraft:swordpedestal:15>,
    <bibliocraft:table>,
    <bibliocraft:table:1>,
    <bibliocraft:table:2>,
    <bibliocraft:table:3>,
    <bibliocraft:table:4>,
    <bibliocraft:table:5>,
    <bibliocraft:table:6>,
    <conarm:invisible_ink>,
    <conarm:resist_mat>,
    <conarm:resist_mat_blast>,
    <conarm:resist_mat_fire>,
    <conarm:resist_mat_proj>,
    <conarm:travel_cloak>,
    <conarm:travel_goggles_base>,
    <conarm:travel_potion>,
    <conarm:travel_sack>,
    <conarm:travel_slowfall>,
    <conarm:travel_sneak>,
    <conarm:travel_soul>,
    <cookingforblockheads:cabinet>,
    <cookingforblockheads:cooking_table>,
    <cookingforblockheads:corner>,
    <cookingforblockheads:counter>,
    <cookingforblockheads:cutting_board>,
    <cookingforblockheads:fruit_basket>,
    <creepingnether:hallowcoal>,
    <creepingnether:hallowgold>,
    <creepingnether:nethercoal>,
    <creepingnether:nethergold>,
    <dynamictrees:dendropotion>,
    <dynamictrees:dendropotion:1>,
    <dynamictrees:dendropotion:2>,
    <dynamictrees:dendropotion:3>,
    <dynamictrees:dendropotion:6>,
    <forestry:butterfly_chest>,
    <forestry:cart.beehouse>,
    <forestry:cart.beehouse:1>,
    <forestry:cocoon>,
    <forestry:cocoon.solid>,
    <forestry:crafting_material:5>,
    <forestry:doors.acacia>,
    <forestry:doors.balsa>,
    <forestry:doors.baobab>,
    <forestry:doors.cherry>,
    <forestry:doors.chestnut>,
    <forestry:doors.citrus>,
    <forestry:doors.cocobolo>,
    <forestry:doors.ebony>,
    <forestry:doors.giganteum>,
    <forestry:doors.greenheart>,
    <forestry:doors.ipe>,
    <forestry:doors.kapok>,
    <forestry:doors.larch>,
    <forestry:doors.lime>,
    <forestry:doors.mahoe>,
    <forestry:doors.mahogany>,
    <forestry:doors.maple>,
    <forestry:doors.padauk>,
    <forestry:doors.palm>,
    <forestry:doors.papaya>,
    <forestry:doors.pine>,
    <forestry:doors.plum>,
    <forestry:doors.poplar>,
    <forestry:doors.sequoia>,
    <forestry:doors.teak>,
    <forestry:doors.walnut>,
    <forestry:doors.wenge>,
    <forestry:doors.willow>,
    <forestry:doors.zebrawood>,
    <forestry:grafter>,
    <forestry:grafter_proven>,
    <forestry:scoop>,
    <forestry:smoker>,
    <forestry:wax_cast>,
    <forestry:worktable>,
//    <golems:golem_head>,
//    <golems:golem_paper>,
    <grapplemod:doubleupgradeitem>,
    <grapplemod:enderhook>,
    <grapplemod:launcheritem>,
    <grapplemod:limitsupgradeitem>,
    <malisisdoors:carriage_door>,
    <malisisdoors:wood_sliding_door>,
    <malisisdoors:shoji_door>,
    <malisisdoors:door_factory>,
    <malisisdoors:jail_door>,
    <malisisdoors:medieval_door>,
    <malisisdoors:saloon>,
    <malisisdoors:big_door_spruce_3x3>,
    <malisisdoors:big_door_oak_3x3>,
    <malisisdoors:big_door_birch_3x3>,
    <malisisdoors:big_door_oak_3x3>,
    <malisisdoors:big_door_jungle_3x3>,
    <malisisdoors:big_door_acacia_3x3>,
    <malisisdoors:big_door_dark_oak_3x3>,
    <malisisdoors:big_door_iron_3x3>,
    <malisisdoors:big_door_rusty_3x3>,
    <minecraft:acacia_boat>,
    <minecraft:acacia_door>,
    <minecraft:anvil:1>,
    <minecraft:anvil:2>,
    <minecraft:armor_stand>,
    <minecraft:beacon>,
    <minecraft:birch_boat>,
    <minecraft:birch_door>,
    <minecraft:blaze_powder>,
    <minecraft:boat>,
    <minecraft:brewing_stand>,
    <minecraft:carpet>,
    <minecraft:carpet:1>,
    <minecraft:carpet:2>,
    <minecraft:carpet:3>,
    <minecraft:carpet:4>,
    <minecraft:carpet:5>,
    <minecraft:carpet:6>,
    <minecraft:carpet:7>,
    <minecraft:carpet:8>,
    <minecraft:carpet:9>,
    <minecraft:carpet:10>,
    <minecraft:carpet:11>,
    <minecraft:carpet:12>,
    <minecraft:carpet:13>,
    <minecraft:carpet:14>,
    <minecraft:carpet:15>,
    <minecraft:cauldron>,
    <minecraft:chainmail_boots>,
    <minecraft:chainmail_chestplate>,
    <minecraft:chainmail_helmet>,
    <minecraft:chainmail_leggings>,
    <minecraft:chest>,
    <minecraft:crafting_table>,
    <minecraft:dark_oak_boat>,
    <minecraft:dark_oak_door>,
    <minecraft:diamond_block>,
    <minecraft:diamond_horse_armor>,
    <minecraft:furnace>,
    <minecraft:ghast_tear>,
    <minecraft:glowstone>,
    <minecraft:glowstone_dust>,
    <minecraft:gold_block>,
    <minecraft:gold_ingot>,
//    <minecraft:gold_nugget>,
    <minecraft:gold_ore>,
    <minecraft:golden_apple>,
    <minecraft:golden_apple:1>,
    <minecraft:golden_carrot>,
    <minecraft:golden_horse_armor>,
    <minecraft:golden_leggings>,
    <minecraft:golden_pickaxe>,
    <minecraft:iron_block>,
    <minecraft:iron_boots>,
    <minecraft:iron_door>,
    <minecraft:iron_helmet>,
    <minecraft:iron_horse_armor>,
    <minecraft:iron_ingot>,
    <minecraft:iron_ore>,
    <minecraft:iron_trapdoor>,
    <minecraft:item_frame>,
    <minecraft:jungle_boat>,
    <minecraft:jungle_door>,
    <minecraft:ladder>,
    <minecraft:lapis_block>,
    <minecraft:lapis_ore>,
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:water"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:mundane"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:thick"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:awkward"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:night_vision"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_night_vision"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:invisibility"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_invisibility"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:leaping"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_leaping"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_leaping"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:fire_resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_fire_resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:swiftness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_swiftness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_swiftness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:slowness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_slowness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:water_breathing"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_water_breathing"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:healing"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_healing"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:harming"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_harming"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:poison"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_poison"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_poison"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:regeneration"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_regeneration"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_regeneration"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strength"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_strength"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:strong_strength"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:weakness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:long_weakness"}),
    <minecraft:lingering_potion>.withTag({Potion: "minecraft:luck"}),
    <minecraft:lingering_potion>.withTag({Potion: "toughasnails:cold_resistance_type"}),
    <minecraft:lingering_potion>.withTag({Potion: "toughasnails:long_cold_resistance_type"}),
    <minecraft:lingering_potion>.withTag({Potion: "toughasnails:heat_resistance_type"}),
    <minecraft:lingering_potion>.withTag({Potion: "toughasnails:long_heat_resistance_type"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:resilience"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:long_resilience"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:strong_resilience"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:haste"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:long_haste"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:strong_haste"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:mining_fatigue"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:long_mining_fatigue"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:strong_mining_fatigue"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:long_resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:strong_resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:danger_sight"}),
    <minecraft:lingering_potion>.withTag({Potion: "quark:long_danger_sight"}),
/*
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_resistance"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:absorption"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_absorption"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_absorption"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:haste"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_haste"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_haste"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:fatigue"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_fatigue"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_fatigue"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:wither"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_wither"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_wither"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:sundering"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_sundering"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_sundering"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:knowledge"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:long_knowledge"}),
    <minecraft:lingering_potion>.withTag({Potion: "apotheosis:strong_knowledge"}),
*/
    <minecraft:lit_pumpkin>,
    <minecraft:nether_star>,
    <minecraft:nether_wart>,
    <minecraft:nether_wart_block>,
    <minecraft:netherbrick>,
    <minecraft:noteblock>,
    <minecraft:painting>,
    <minecraft:potion>.withTag({Potion: "minecraft:mundane"}),
    <minecraft:potion>.withTag({Potion: "minecraft:thick"}),
    <minecraft:potion>.withTag({Potion: "minecraft:awkward"}),
    <minecraft:potion>.withTag({Potion: "minecraft:night_vision"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_night_vision"}),
    <minecraft:potion>.withTag({Potion: "minecraft:invisibility"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_invisibility"}),
    <minecraft:potion>.withTag({Potion: "minecraft:leaping"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_leaping"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_leaping"}),
    <minecraft:potion>.withTag({Potion: "minecraft:fire_resistance"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_fire_resistance"}),
    <minecraft:potion>.withTag({Potion: "minecraft:swiftness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_swiftness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_swiftness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:slowness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_slowness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:water_breathing"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_water_breathing"}),
    <minecraft:potion>.withTag({Potion: "minecraft:healing"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_healing"}),
    <minecraft:potion>.withTag({Potion: "minecraft:harming"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_harming"}),
    <minecraft:potion>.withTag({Potion: "minecraft:poison"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_poison"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_poison"}),
    <minecraft:potion>.withTag({Potion: "minecraft:regeneration"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_regeneration"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_regeneration"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strength"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_strength"}),
    <minecraft:potion>.withTag({Potion: "minecraft:strong_strength"}),
    <minecraft:potion>.withTag({Potion: "minecraft:weakness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:long_weakness"}),
    <minecraft:potion>.withTag({Potion: "minecraft:luck"}),
    <minecraft:potion>.withTag({Potion: "toughasnails:cold_resistance_type"}),
    <minecraft:potion>.withTag({Potion: "toughasnails:long_cold_resistance_type"}),
    <minecraft:potion>.withTag({Potion: "toughasnails:heat_resistance_type"}),
    <minecraft:potion>.withTag({Potion: "toughasnails:long_heat_resistance_type"}),
    <minecraft:potion>.withTag({Potion: "quark:resilience"}),
    <minecraft:potion>.withTag({Potion: "quark:long_resilience"}),
    <minecraft:potion>.withTag({Potion: "quark:strong_resilience"}),
    <minecraft:potion>.withTag({Potion: "quark:haste"}),
    <minecraft:potion>.withTag({Potion: "quark:long_haste"}),
    <minecraft:potion>.withTag({Potion: "quark:strong_haste"}),
    <minecraft:potion>.withTag({Potion: "quark:mining_fatigue"}),
    <minecraft:potion>.withTag({Potion: "quark:long_mining_fatigue"}),
    <minecraft:potion>.withTag({Potion: "quark:strong_mining_fatigue"}),
    <minecraft:potion>.withTag({Potion: "quark:resistance"}),
    <minecraft:potion>.withTag({Potion: "quark:long_resistance"}),
    <minecraft:potion>.withTag({Potion: "quark:strong_resistance"}),
    <minecraft:potion>.withTag({Potion: "quark:danger_sight"}),
    <minecraft:potion>.withTag({Potion: "quark:long_danger_sight"}),
/*
    <minecraft:potion>.withTag({Potion: "apotheosis:resistance"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_resistance"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_resistance"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:absorption"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_absorption"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_absorption"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:haste"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_haste"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_haste"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:fatigue"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_fatigue"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_fatigue"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:wither"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_wither"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_wither"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:sundering"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_sundering"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_sundering"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:knowledge"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:long_knowledge"}),
    <minecraft:potion>.withTag({Potion: "apotheosis:strong_knowledge"}),
*/
    <minecraft:splash_potion>.withTag({Potion: "minecraft:water"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:mundane"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:thick"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:awkward"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:night_vision"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_night_vision"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:invisibility"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_invisibility"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:leaping"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_leaping"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_leaping"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:fire_resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_fire_resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:swiftness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_swiftness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_swiftness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:slowness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_slowness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:water_breathing"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_water_breathing"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:healing"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_healing"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:harming"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_harming"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:poison"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_poison"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_poison"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:regeneration"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_regeneration"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_regeneration"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strength"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_strength"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:strong_strength"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:weakness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:long_weakness"}),
    <minecraft:splash_potion>.withTag({Potion: "minecraft:luck"}),
    <minecraft:splash_potion>.withTag({Potion: "toughasnails:cold_resistance_type"}),
    <minecraft:splash_potion>.withTag({Potion: "toughasnails:long_cold_resistance_type"}),
    <minecraft:splash_potion>.withTag({Potion: "toughasnails:heat_resistance_type"}),
    <minecraft:splash_potion>.withTag({Potion: "toughasnails:long_heat_resistance_type"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:resilience"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:long_resilience"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:strong_resilience"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:haste"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:long_haste"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:strong_haste"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:mining_fatigue"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:long_mining_fatigue"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:strong_mining_fatigue"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:long_resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:strong_resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:danger_sight"}),
    <minecraft:splash_potion>.withTag({Potion: "quark:long_danger_sight"}),
/*
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_resistance"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:absorption"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_absorption"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_absorption"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:haste"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_haste"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_haste"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:fatigue"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_fatigue"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_fatigue"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:wither"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_wither"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_wither"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:sundering"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_sundering"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_sundering"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:knowledge"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:long_knowledge"}),
    <minecraft:splash_potion>.withTag({Potion: "apotheosis:strong_knowledge"}),
*/
    <minecraft:spruce_boat>,
    <minecraft:spruce_door>,
    <minecraft:stained_glass>,
    <minecraft:stained_glass:1>,
    <minecraft:stained_glass:2>,
    <minecraft:stained_glass:3>,
    <minecraft:stained_glass:4>,
    <minecraft:stained_glass:5>,
    <minecraft:stained_glass:6>,
    <minecraft:stained_glass:7>,
    <minecraft:stained_glass:8>,
    <minecraft:stained_glass:9>,
    <minecraft:stained_glass:10>,
    <minecraft:stained_glass:11>,
    <minecraft:stained_glass:12>,
    <minecraft:stained_glass:13>,
    <minecraft:stained_glass:14>,
    <minecraft:stained_glass:15>,
    <minecraft:stained_glass_pane>,
    <minecraft:stained_glass_pane:1>,
    <minecraft:stained_glass_pane:2>,
    <minecraft:stained_glass_pane:3>,
    <minecraft:stained_glass_pane:4>,
    <minecraft:stained_glass_pane:5>,
    <minecraft:stained_glass_pane:6>,
    <minecraft:stained_glass_pane:7>,
    <minecraft:stained_glass_pane:8>,
    <minecraft:stained_glass_pane:9>,
    <minecraft:stained_glass_pane:10>,
    <minecraft:stained_glass_pane:11>,
    <minecraft:stained_glass_pane:12>,
    <minecraft:stained_glass_pane:13>,
    <minecraft:stained_glass_pane:14>,
    <minecraft:stained_glass_pane:15>,
    <minecraft:stonebrick>,
    <minecraft:stonebrick:1>,
    <minecraft:stonebrick:2>,
    <minecraft:stonebrick:3>,
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:night_vision"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_night_vision"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:invisibility"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_invisibility"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:leaping"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_leaping"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_leaping"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:fire_resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_fire_resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:swiftness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_swiftness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_swiftness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:slowness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_slowness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:water_breathing"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_water_breathing"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:healing"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_healing"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:harming"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_harming"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:poison"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_poison"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_poison"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:regeneration"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_regeneration"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_regeneration"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strength"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_strength"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:strong_strength"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:weakness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:long_weakness"}),
    <minecraft:tipped_arrow>.withTag({Potion: "minecraft:luck"}),
    <minecraft:tipped_arrow>.withTag({Potion: "toughasnails:cold_resistance_type"}),
    <minecraft:tipped_arrow>.withTag({Potion: "toughasnails:long_cold_resistance_type"}),
    <minecraft:tipped_arrow>.withTag({Potion: "toughasnails:heat_resistance_type"}),
    <minecraft:tipped_arrow>.withTag({Potion: "toughasnails:long_heat_resistance_type"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:resilience"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:long_resilience"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:strong_resilience"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:haste"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:long_haste"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:strong_haste"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:mining_fatigue"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:long_mining_fatigue"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:strong_mining_fatigue"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:long_resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:strong_resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:danger_sight"}),
    <minecraft:tipped_arrow>.withTag({Potion: "quark:long_danger_sight"}),
/*
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_resistance"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:absorption"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_absorption"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_absorption"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:haste"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_haste"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_haste"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:fatigue"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_fatigue"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_fatigue"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:wither"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_wither"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_wither"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:sundering"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_sundering"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_sundering"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:knowledge"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:long_knowledge"}),
    <minecraft:tipped_arrow>.withTag({Potion: "apotheosis:strong_knowledge"}),
*/
    <minecraft:totem_of_undying>,
    <minecraft:trapdoor>,
    <minecraft:trapped_chest>,
    <minecraft:wooden_button>,
    <minecraft:wooden_door>,
    <mysticalworld:spindle>,
//    <openblocks:auto_anvil>,
    <malisisdoors:customdooritem>,
//    <openblocks:auto_enchantment_table>,
    <primal:door_corypha>,
    <primal:door_ironwood>,
    <primal:door_yew>,
    <primal:door_lacquer>,
    <quark:custom_chest>,
    <quark:custom_chest:1>,
    <quark:custom_chest:2>,
    <quark:custom_chest:3>,
    <quark:custom_chest:4>,
    <quark:custom_chest_trap>,
    <quark:custom_chest_trap:1>,
    <quark:custom_chest_trap:2>,
    <quark:custom_chest_trap:3>,
    <quark:custom_chest_trap:4>,
    <quark:pirate_hat>,
    <quark:acacia_trapdoor>,
    <quark:birch_trapdoor>,
    <quark:dark_oak_trapdoor>,
    <quark:jungle_trapdoor>,
    <quark:spruce_trapdoor>,
    <roots:wildwood_trapdoor>,
    <roots:wildwood_door>,
    <rustic:apple_juice>,
    <rustic:barrel>,
    <rustic:brewing_barrel>,
    <rustic:cabinet>,
    <rustic:candle>,
    <rustic:candle_gold>,
    <rustic:candle_lever>,
    <rustic:candle_lever_gold>,
    <rustic:candle_lever_silver>,
    <rustic:candle_silver>,
    <rustic:chain>,
    <rustic:chain_gold>,
    <rustic:chain_silver>,
    <rustic:chandelier>,
    <rustic:chandelier_gold>,
    <rustic:chandelier_silver>,
    <rustic:clay_wall>,
    <rustic:clay_wall_cross>,
    <rustic:clay_wall_diag>,
    <rustic:condenser>,
    <rustic:condenser_advanced>,
    <rustic:crushing_tub>,
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:instant_health", Duration: 1, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:instant_health", Duration: 1, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:regeneration", Duration: 900, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:regeneration", Duration: 1800, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:regeneration", Duration: 450, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:wither", Duration: 900, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:wither", Duration: 1800, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:wither", Duration: 450, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:night_vision", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:night_vision", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:speed", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:speed", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:speed", Duration: 1800, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:fire_resistance", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:fire_resistance", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:health_boost", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:health_boost", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:health_boost", Duration: 1800, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:haste", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:haste", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:haste", Duration: 1800, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strength", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strength", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "minecraft:strength", Duration: 1800, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:ironskin", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:ironskin", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:ironskin", Duration: 1800, Amplifier: 1}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:feather", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:feather", Duration: 9600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:blazing_trail", Duration: 3600, Amplifier: 0}]}),
    <rustic:elixir>.withTag({ElixirEffects: [{Effect: "rustic:blazing_trail", Duration: 9600, Amplifier: 0}]}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "juniper_berry_juice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "elderberry_juice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wormwood_mixture", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "sage_juice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "gin", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "elderberry_wine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "absinthe", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "sage_liqueur", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "oliveoil", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ironberryjuice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wildberryjuice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "grapejuice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "applejuice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "alewort", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "for.honey", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ale", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "cider", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "ironwine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "mead", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wildberrywine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "wine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "cinderfire_whiskey", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "cinderfire_wort", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "shimmerdew_wort", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "shimmerdew_spirits", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "viscous_wort", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "viscous_brew", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "peach_juice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "pear_juice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "persimmon_juice", Amount: 1000}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "peach_schnapps", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "perry", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:fluid_bottle>.withTag({Fluid: {FluidName: "persimmon_wine", Amount: 1000, Tag: {Quality: 0.75 as float}}}),
    <rustic:gargoyle>,
    <rustic:golden_lantern>,
    <rustic:granite_pillar>,
    <rustic:grape_juice>,
    <rustic:grape_stem>,
    <rustic:iron_lantern>,
    <rustic:iron_lattice>,
    <rustic:ironberries>,
    <rustic:ironberry_juice>,
    <rustic:ironwood_door>,
    <rustic:lantern_wood>,
    <rustic:liquid_barrel>,
    <rustic:marsh_mallow>,
    <rustic:mooncap_mushroom>,
    <rustic:olive_door>,
    <rustic:painted_wood_black>,
    <rustic:painted_wood_blue>,
    <rustic:painted_wood_brown>,
    <rustic:painted_wood_cyan>,
    <rustic:painted_wood_gray>,
    <rustic:painted_wood_green>,
    <rustic:painted_wood_light_blue>,
    <rustic:painted_wood_lime>,
    <rustic:painted_wood_magenta>,
    <rustic:painted_wood_orange>,
    <rustic:painted_wood_pink>,
    <rustic:painted_wood_purple>,
    <rustic:painted_wood_red>,
    <rustic:painted_wood_silver>,
    <rustic:painted_wood_white>,
    <rustic:painted_wood_yellow>,
    <rustic:retort>,
    <rustic:retort_advanced>,
    <rustic:silver_lantern>,
    <rustic:wildberry_juice>,
    <rusticatedfruit:peach_juice>,
    <rusticatedfruit:pear_juice>,
    <rusticatedfruit:persimmon_juice>,
    <rusticthaumaturgy:candle_brass>,
    <rusticthaumaturgy:chain_brass>,
    <rusticthaumaturgy:chair_greatwood>,
    <rusticthaumaturgy:chair_silverwood>,
    <rusticthaumaturgy:cinderfire_whiskey>,
    <rusticthaumaturgy:cinderfire_wort>,
    <rusticthaumaturgy:cindermote>,
    <rusticthaumaturgy:cindermote_seeds>,
    <rusticthaumaturgy:dust_tiny_blaze>,
    <rusticthaumaturgy:lantern_brass>,
    <rusticthaumaturgy:shimmerdew_spirits>,
    <rusticthaumaturgy:shimmerdew_wort>,
    <rusticthaumaturgy:shimmerpetal>,
    <rusticthaumaturgy:shimmerpetal_bulb>,
    <rusticthaumaturgy:table_greatwood>,
    <rusticthaumaturgy:table_silverwood>,
    <rusticthaumaturgy:viscap>,
    <rusticthaumaturgy:viscap_spores>,
    <rusticthaumaturgy:viscous_brew>,
    <rusticthaumaturgy:viscous_wort>,
    <slabmachines:chest_slab>,
    <slabmachines:crafting_station_slab>,
    <slabmachines:furnace_slab>,
    <slabmachines:note_slab>,
    <slabmachines:part_chest_slab>,
    <slabmachines:tool_forge_slab>,
    <slabmachines:workbench_slab>,
    <storagedrawers:basicdrawers>.withTag({material: "oak"}),
    <storagedrawers:basicdrawers>.withTag({material: "spruce"}),
    <storagedrawers:basicdrawers>.withTag({material: "birch"}),
    <storagedrawers:basicdrawers>.withTag({material: "jungle"}),
    <storagedrawers:basicdrawers>.withTag({material: "acacia"}),
    <storagedrawers:basicdrawers>.withTag({material: "dark_oak"}),
    <storagedrawers:basicdrawers:1>.withTag({material: "oak"}),
    <storagedrawers:basicdrawers:1>.withTag({material: "spruce"}),
    <storagedrawers:basicdrawers:1>.withTag({material: "birch"}),
    <storagedrawers:basicdrawers:1>.withTag({material: "jungle"}),
    <storagedrawers:basicdrawers:1>.withTag({material: "acacia"}),
    <storagedrawers:basicdrawers:1>.withTag({material: "dark_oak"}),
    <storagedrawers:basicdrawers:2>.withTag({material: "oak"}),
    <storagedrawers:basicdrawers:2>.withTag({material: "spruce"}),
    <storagedrawers:basicdrawers:2>.withTag({material: "birch"}),
    <storagedrawers:basicdrawers:2>.withTag({material: "jungle"}),
    <storagedrawers:basicdrawers:2>.withTag({material: "acacia"}),
    <storagedrawers:basicdrawers:2>.withTag({material: "dark_oak"}),
    <storagedrawers:basicdrawers:3>.withTag({material: "oak"}),
    <storagedrawers:basicdrawers:3>.withTag({material: "spruce"}),
    <storagedrawers:basicdrawers:3>.withTag({material: "birch"}),
    <storagedrawers:basicdrawers:3>.withTag({material: "jungle"}),
    <storagedrawers:basicdrawers:3>.withTag({material: "acacia"}),
    <storagedrawers:basicdrawers:3>.withTag({material: "dark_oak"}),
    <storagedrawers:basicdrawers:4>.withTag({material: "oak"}),
    <storagedrawers:basicdrawers:4>.withTag({material: "spruce"}),
    <storagedrawers:basicdrawers:4>.withTag({material: "birch"}),
    <storagedrawers:basicdrawers:4>.withTag({material: "jungle"}),
    <storagedrawers:basicdrawers:4>.withTag({material: "acacia"}),
    <storagedrawers:basicdrawers:4>.withTag({material: "dark_oak"}),
    <storagedrawers:compdrawers>,
    <storagedrawers:controller>,
    <storagedrawers:controllerslave>,
    <storagedrawers:customdrawers>,
    <storagedrawers:customdrawers:1>,
    <storagedrawers:customdrawers:2>,
    <storagedrawers:customdrawers:3>,
    <storagedrawers:customdrawers:4>,
    <storagedrawers:customtrim>,
    <storagedrawers:drawer_key>,
    <storagedrawers:framingtable>,
    <storagedrawers:keybutton>,
    <storagedrawers:keybutton:1>,
    <storagedrawers:keybutton:2>,
    <storagedrawers:keybutton:3>,
    <storagedrawers:personal_key>,
    <storagedrawers:quantify_key>,
    <storagedrawers:shroud_key>,
    <storagedrawers:tape>,
    <storagedrawers:trim>,
    <storagedrawers:trim:1>,
    <storagedrawers:trim:2>,
    <storagedrawers:trim:3>,
    <storagedrawers:trim:4>,
    <storagedrawers:trim:5>,
    <storagedrawers:upgrade_conversion>,
    <storagedrawers:upgrade_one_stack>,
    <storagedrawers:upgrade_status>,
    <storagedrawers:upgrade_status:1>,
    <storagedrawers:upgrade_storage>,
    <storagedrawers:upgrade_storage:1>,
    <storagedrawers:upgrade_storage:2>,
    <storagedrawers:upgrade_storage:3>,
    <storagedrawers:upgrade_storage:4>,
    <storagedrawers:upgrade_template>,
    <storagedrawers:upgrade_void>,
    <t3s4ebw:crystal_crop>,
    <tcomplement:alloy_tank>,
    <tcomplement:porcelain_alloy_tank>,
    <tcomplement:porcelain_casting>,
    <tcomplement:porcelain_casting:1>,
    <tcomplement:porcelain_melter>,
    <tcomplement:porcelain_melter:8>,
    <tcomplement:porcelain_tank>,
    <tcomplement:porcelain_tank:1>,
    <tcomplement:porcelain_tank:2>,
    <tconstruct:fancy_frame>,
    <tconstruct:fancy_frame:1>,
    <tconstruct:fancy_frame:2>,
    <tconstruct:fancy_frame:3>,
    <tconstruct:fancy_frame:4>,
    <tconstruct:fancy_frame:5>,
    <tconstruct:fancy_frame:6>,
    <tconstruct:ingots>,
    <tconstruct:ingots:1>,
    <tconstruct:ingots:2>,
    <tconstruct:ingots:3>,
    <tconstruct:ingots:4>,
    <tconstruct:materials:14>,
    <tconstruct:materials:15>,
    <tconstruct:materials:16>,
    <tconstruct:materials:18>,
    <tconstruct:materials:19>,
    <tconstruct:metal>,
    <tconstruct:metal:1>,
    <tconstruct:metal:2>,
    <tconstruct:metal:3>,
    <tconstruct:metal:4>,
    <tconstruct:metal:5>,
    <tconstruct:metal:6>,
    <tconstruct:moms_spaghetti>,
    <tconstruct:nuggets>,
    <tconstruct:nuggets:1>,
    <tconstruct:nuggets:2>,
    <tconstruct:nuggets:3>,
    <tconstruct:nuggets:4>,
    <tconstruct:nuggets:5>,
    <tconstruct:ore>,
    <tconstruct:ore:1>,
    <tconstruct:smeltery_io>,
    <tconstruct:spaghetti>,
    <tconstruct:tinker_tank_controller>,
    <telepastries:twilight_cake>,
    <toughasnails:fruit_juice:1>,
    <toughasnails:fruit_juice:2>,
    <toughasnails:fruit_juice:4>,
    <toughasnails:fruit_juice:5>,
    <toughasnails:fruit_juice:6>,
    <toughasnails:fruit_juice:7>,
    <toughasnails:fruit_juice:9>,
    <toughasnails:jelled_slime>,
    <toughasnails:magma_shard>,
    <toughasnails:thermometer>,
    <twilightforest:alpha_fur>,
    <twilightforest:armor_shard>,
    <twilightforest:armor_shard_cluster>,
    <twilightforest:aurora_block>,
    <twilightforest:aurora_pillar>,
    <twilightforest:aurora_slab>,
    <twilightforest:auroralized_glass>,
    <twilightforest:block_and_chain>,
    <twilightforest:block_storage>,
    <twilightforest:block_storage:1>,
    <twilightforest:block_storage:2>,
    <twilightforest:block_storage:3>,
    <twilightforest:block_storage:4>,
    <twilightforest:borer_essence>,
    <twilightforest:boss_spawner>,
    <twilightforest:boss_spawner:1>,
    <twilightforest:boss_spawner:2>,
    <twilightforest:boss_spawner:3>,
    <twilightforest:boss_spawner:4>,
    <twilightforest:boss_spawner:5>,
    <twilightforest:boss_spawner:6>,
    <twilightforest:boss_spawner:7>,
    <twilightforest:boss_spawner:9>,
    <twilightforest:burnt_thorns>,
    <twilightforest:canopy_button>,
    <twilightforest:canopy_door>,
    <twilightforest:canopy_fence>,
    <twilightforest:canopy_gate>,
    <twilightforest:canopy_planks>,
    <twilightforest:canopy_plate>,
    <twilightforest:canopy_slab>,
    <twilightforest:canopy_stairs>,
    <twilightforest:canopy_trapdoor>,
    <twilightforest:carminite>,
    <twilightforest:castle_brick>,
    <twilightforest:castle_brick:1>,
    <twilightforest:castle_brick:2>,
    <twilightforest:castle_brick:3>,
    <twilightforest:castle_brick:4>,
    <twilightforest:castle_brick:5>,
    <twilightforest:castle_door>,
    <twilightforest:castle_door:1>,
    <twilightforest:castle_door:2>,
    <twilightforest:castle_door:3>,
    <twilightforest:castle_pillar>,
    <twilightforest:castle_pillar:1>,
    <twilightforest:castle_pillar:2>,
    <twilightforest:castle_pillar:3>,
    <twilightforest:castle_rune_brick>,
    <twilightforest:castle_rune_brick:1>,
    <twilightforest:castle_rune_brick:2>,
    <twilightforest:castle_rune_brick:3>,
    <twilightforest:castle_stairs>,
    <twilightforest:castle_stairs:8>,
    <twilightforest:castle_stairs_brick>,
    <twilightforest:castle_stairs_cracked>,
    <twilightforest:castle_stairs_mossy>,
    <twilightforest:castle_stairs_worn>,
    <twilightforest:charm_of_keeping_1>,
    <twilightforest:charm_of_keeping_2>,
    <twilightforest:charm_of_keeping_3>,
    <twilightforest:charm_of_life_1>,
    <twilightforest:charm_of_life_2>,
    <twilightforest:cicada>,
    <twilightforest:cinder_furnace>,
    <twilightforest:cinder_log>,
    <twilightforest:cooked_meef>,
    <twilightforest:cooked_venison>,
    <twilightforest:crumble_horn>,
    <twilightforest:cube_of_annihilation>,
    <twilightforest:cube_talisman>,
    <twilightforest:dark_button>,
    <twilightforest:dark_door>,
    <twilightforest:dark_fence>,
    <twilightforest:dark_gate>,
    <twilightforest:dark_leaves>,
    <twilightforest:dark_planks>,
    <twilightforest:dark_plate>,
    <twilightforest:dark_slab>,
    <twilightforest:dark_stairs>,
    <twilightforest:dark_trapdoor>,
    <twilightforest:deadrock>,
    <twilightforest:deadrock:1>,
    <twilightforest:deadrock:2>,
    <twilightforest:ender_bow>,
    <twilightforest:etched_nagastone>,
    <twilightforest:etched_nagastone_mossy>,
    <twilightforest:etched_nagastone_weathered>,
    <twilightforest:experiment_115>,
    <twilightforest:fiery_blood>,
    <twilightforest:fiery_ingot>,
    <twilightforest:fiery_tears>,
    <twilightforest:fire_jet>,
    <twilightforest:fire_jet:3>,
    <twilightforest:fire_jet:1>,
    <twilightforest:fire_jet:6>,
    <twilightforest:firefly>,
    <twilightforest:firefly_jar>,
    <twilightforest:fluffy_cloud>,
    <twilightforest:force_field>,
    <twilightforest:force_field:1>,
    <twilightforest:force_field:2>,
    <twilightforest:force_field:3>,
    <twilightforest:force_field:4>,
    <twilightforest:giant_cobblestone>,
    <twilightforest:giant_leaves>,
    <twilightforest:giant_log>,
    <twilightforest:giant_obsidian>,
    <twilightforest:giant_pickaxe>,
    <twilightforest:giant_sword>,
    <twilightforest:glass_sword>,
    <twilightforest:glass_sword>.withTag({Unbreakable: 1 as byte}),
    <twilightforest:hedge>,
    <twilightforest:huge_lilypad>,
    <twilightforest:huge_mushgloom>,
    <twilightforest:huge_stalk>,
    <twilightforest:huge_waterlily>,
    <twilightforest:hydra_chop>,
    <twilightforest:ice_bomb>,
    <twilightforest:ice_bow>,
    <twilightforest:ice_sword>,
    <twilightforest:iron_ladder>,
    <twilightforest:ironwood_raw>,
    <twilightforest:knightmetal_ingot>,
    <twilightforest:knightmetal_shield>,
    <twilightforest:lamp_of_cinders>,
    <twilightforest:lifedrain_scepter>,
    <twilightforest:liveroot>,
    <twilightforest:magic_beans>,
    <twilightforest:magic_leaves>,
    <twilightforest:magic_leaves:1>,
    <twilightforest:magic_leaves:2>,
    <twilightforest:magic_leaves:3>,
    <twilightforest:magic_log>,
    <twilightforest:magic_log:1>,
    <twilightforest:magic_log:2>,
    <twilightforest:magic_log:3>,
    <twilightforest:magic_log_core>,
    <twilightforest:magic_log_core:1>,
    <twilightforest:magic_log_core:2>,
    <twilightforest:magic_log_core:3>,
    <twilightforest:magic_map>,
    <twilightforest:magic_map_empty>,
    <twilightforest:magic_map_focus>,
    <twilightforest:mangrove_button>,
    <twilightforest:mangrove_door>,
    <twilightforest:mangrove_fence>,
    <twilightforest:mangrove_gate>,
    <twilightforest:mangrove_planks>,
    <twilightforest:mangrove_plate>,
    <twilightforest:mangrove_slab>,
    <twilightforest:mangrove_stairs>,
    <twilightforest:mangrove_trapdoor>,
    <twilightforest:maze_map>,
    <twilightforest:maze_map_empty>,
    <twilightforest:maze_map_focus>,
    <twilightforest:maze_stone>,
    <twilightforest:maze_stone:1>,
    <twilightforest:maze_stone:2>,
    <twilightforest:maze_stone:3>,
    <twilightforest:maze_stone:4>,
    <twilightforest:maze_stone:5>,
    <twilightforest:maze_stone:6>,
    <twilightforest:maze_stone:7>,
    <twilightforest:maze_wafer>,
    <twilightforest:mazebreaker_pickaxe>.withTag({ench: [{lvl: 4 as short, id: 32}, {lvl: 3 as short, id: 34}, {lvl: 2 as short, id: 35}]}),
    <twilightforest:meef_stroganoff>,
    <twilightforest:mine_button>,
    <twilightforest:mine_door>,
    <twilightforest:mine_fence>,
    <twilightforest:mine_gate>,
    <twilightforest:mine_planks>,
    <twilightforest:mine_plate>,
    <twilightforest:mine_slab>,
    <twilightforest:mine_stairs>,
    <twilightforest:mine_trapdoor>,
    <twilightforest:minotaur_axe>,
    <twilightforest:minotaur_axe_gold>,
    <twilightforest:moon_dial>,
    <twilightforest:moonworm>,
    <twilightforest:moonworm_queen>,
    <twilightforest:naga_chestplate>.withTag({ench: [{lvl: 3 as short, id: 1}]}),
    <twilightforest:naga_leggings>.withTag({ench: [{lvl: 3 as short, id: 0}]}),
    <twilightforest:naga_scale>,
    <twilightforest:naga_stone>,
    <twilightforest:naga_stone:1>,
    <twilightforest:nagastone_pillar>,
    <twilightforest:nagastone_pillar_mossy>,
    <twilightforest:nagastone_pillar_weathered>,
    <twilightforest:nagastone_stairs>,
    <twilightforest:nagastone_stairs:8>,
    <twilightforest:nagastone_stairs_mossy>,
    <twilightforest:nagastone_stairs_mossy:8>,
    <twilightforest:nagastone_stairs_weathered>,
    <twilightforest:nagastone_stairs_weathered:8>,
    <twilightforest:ore_magnet>,
    <twilightforest:ore_map>,
    <twilightforest:ore_map_empty>,
    <twilightforest:ore_meter>,
    <twilightforest:peacock_fan>,
    <twilightforest:phantom_chestplate>,
    <twilightforest:phantom_helmet>,
    <twilightforest:raven_feather>,
    <twilightforest:raw_meef>,
    <twilightforest:raw_venison>,
    <twilightforest:root>,
    <twilightforest:root:1>,
    <twilightforest:seeker_bow>,
    <twilightforest:shader>,
    <twilightforest:shader_bag>,
    <twilightforest:shield_scepter>,
    <twilightforest:slider>,
    <twilightforest:slider:1>,
    <twilightforest:slider:2>,
    <twilightforest:slider:3>,
    <twilightforest:sort_button>,
    <twilightforest:sort_door>,
    <twilightforest:sort_fence>,
    <twilightforest:sort_gate>,
    <twilightforest:sort_planks>,
    <twilightforest:sort_plate>,
    <twilightforest:sort_slab>,
    <twilightforest:sort_stairs>,
    <twilightforest:sort_trapdoor>,
    <twilightforest:spiral_bricks>,
    <twilightforest:steeleaf_ingot>,
    <twilightforest:stone_twist>,
    <twilightforest:stone_twist_thin>,
    <twilightforest:stronghold_shield>,
    <twilightforest:terrorcotta_circle>,
    <twilightforest:terrorcotta_diagonal>,
    <twilightforest:thorn_rose>,
    <twilightforest:thorns>,
    <twilightforest:thorns:1>,
    <twilightforest:time_button>,
    <twilightforest:time_door>,
    <twilightforest:time_fence>,
    <twilightforest:time_gate>,
    <twilightforest:time_planks>,
    <twilightforest:time_plate>,
    <twilightforest:time_slab>,
    <twilightforest:time_stairs>,
    <twilightforest:time_trapdoor>,
    <twilightforest:twilight_oak_trapdoor>,
    <twilightforest:canopy_trapdoor>,
    <twilightforest:mangrove_trapdoor>,
    <twilightforest:dark_trapdoor>,
    <twilightforest:time_trapdoor>,
    <twilightforest:trans_trapdoor>,
    <twilightforest:mine_trapdoor>,
    <twilightforest:sort_trapdoor>,
    <twilightforest:torchberries>,
    <twilightforest:tower_device>,
    <twilightforest:tower_device:2>,
    <twilightforest:tower_device:4>,
    <twilightforest:tower_device:5>,
    <twilightforest:tower_device:6>,
    <twilightforest:tower_device:9>,
    <twilightforest:tower_device:10>,
    <twilightforest:tower_device:12>,
    <twilightforest:tower_key>,
    <twilightforest:tower_translucent>,
    <twilightforest:tower_wood>,
    <twilightforest:tower_wood:1>,
    <twilightforest:tower_wood:2>,
    <twilightforest:tower_wood:3>,
    <twilightforest:tower_wood:4>,
    <twilightforest:trans_button>,
    <twilightforest:trans_door>,
    <twilightforest:trans_fence>,
    <twilightforest:trans_gate>,
    <twilightforest:trans_planks>,
    <twilightforest:trans_plate>,
    <twilightforest:trans_slab>,
    <twilightforest:trans_stairs>,
    <twilightforest:trans_trapdoor>,
    <twilightforest:transformation_powder>,
    <twilightforest:triple_bow>,
    <twilightforest:trollber>,
    <twilightforest:trollsteinn>,
    <twilightforest:trollvidr>,
    <twilightforest:trophy>,
    <twilightforest:trophy:1>,
    <twilightforest:trophy:2>,
    <twilightforest:trophy:3>,
    <twilightforest:trophy:4>,
    <twilightforest:trophy:5>,
    <twilightforest:trophy:6>,
    <twilightforest:trophy:8>,
    <twilightforest:trophy_pedestal>,
    <twilightforest:twilight_leaves>,
    <twilightforest:twilight_leaves:1>,
    <twilightforest:twilight_leaves:2>,
    <twilightforest:twilight_leaves:3>,
    <twilightforest:twilight_leaves_3>,
    <twilightforest:twilight_leaves_3:1>,
    <twilightforest:twilight_log>,
    <twilightforest:twilight_log:1>,
    <twilightforest:twilight_log:2>,
    <twilightforest:twilight_log:3>,
    <twilightforest:twilight_oak_button>,
    <twilightforest:twilight_oak_door>,
    <twilightforest:twilight_oak_fence>,
    <twilightforest:twilight_oak_gate>,
    <twilightforest:twilight_oak_planks>,
    <twilightforest:twilight_oak_plate>,
    <twilightforest:twilight_oak_slab>,
    <twilightforest:twilight_oak_stairs>,
    <twilightforest:twilight_oak_trapdoor>,
    <twilightforest:twilight_plant>,
    <twilightforest:twilight_plant:1>,
    <twilightforest:twilight_plant:2>,
    <twilightforest:twilight_plant:3>,
    <twilightforest:twilight_plant:4>,
    <twilightforest:twilight_plant:5>,
    <twilightforest:twilight_plant:6>,
    <twilightforest:twilight_plant:7>,
    <twilightforest:twilight_plant:8>,
    <twilightforest:twilight_plant:9>,
    <twilightforest:twilight_sapling>,
    <twilightforest:twilight_sapling:1>,
    <twilightforest:twilight_sapling:2>,
    <twilightforest:twilight_sapling:3>,
    <twilightforest:twilight_sapling:4>,
    <twilightforest:twilight_sapling:5>,
    <twilightforest:twilight_sapling:6>,
    <twilightforest:twilight_sapling:7>,
    <twilightforest:twilight_sapling:8>,
    <twilightforest:twilight_sapling:9>,
    <twilightforest:twilight_scepter>,
    <twilightforest:uberous_soil>,
    <twilightforest:uncrafting_table>,
    <twilightforest:underbrick>,
    <twilightforest:underbrick:1>,
    <twilightforest:underbrick:2>,
    <twilightforest:underbrick:3>,
    <twilightforest:unripe_trollber>,
    <twilightforest:wispy_cloud>,
    <twilightforest:zombie_scepter>,
    <villagermarket:villager_market>,
    <wolfarmor:chainmail_wolf_armor>,
    <wolfarmor:diamond_wolf_armor>,
    <progressiontweaks:machine_frame>
];


for entry in medievalIngredients{
    mods.ItemStages.addItemStage("medieval", entry);
    mods.recipestages.Recipes.setRecipeStage("medieval", entry);
	//get string
	var name = entry.commandString as string;
	var length = name.length();
	length = length - 1;
	mods.ltt.LootTable.removeGlobalItem(name.substring(1,length));
}