import crafttweaker.item.IIngredient;


mods.jmapstages.JMapStages.setWaypointStage("exploration");
mods.jmapstages.JMapStages.setFullscreenStage("exploration");
mods.jmapstages.JMapStages.setDeathpointStage("exploration");
mods.jmapstages.JMapStages.setMinimapStage("exploration");


mods.ItemStages.stageModItems("modern","immersivepetroleum");
mods.ItemStages.stageModItems("modern","mts");
mods.ItemStages.stageModItems("modern","scannable");
mods.ItemStages.stageModItems("modern","projectred-fabrication");
mods.ItemStages.stageModItems("modern","projectred-integration");
mods.ItemStages.stageModItems("modern","projectred-transmission");

var modernIngredients as IIngredient[] = [
    <animania:block_hamster_wheel>,
    <bibliocraft:handdrill>,
    <bibliocraft:discrack>,
    <bibliocraft:cookiejar>,
    <bibliocraft:tape>,
    <bibliocraft:bibliodrill>,
    <bibliocraft:tapemeasure>,
    <bibliocraft:dinnerplate>,

    <cookingforblockheads:fridge>,
    <cookingforblockheads:heating_unit>,
    <cookingforblockheads:ice_unit>,
    <cookingforblockheads:kitchen_floor>,
    <cookingforblockheads:oven>,
    <cookingforblockheads:preservation_chamber>,
    <cookingforblockheads:sink>,
    <cookingforblockheads:toaster>,

    <minecraft:concrete:1>,
    <minecraft:concrete:2>,
    <minecraft:concrete:3>,
    <minecraft:concrete:4>,
    <minecraft:concrete:5>,
    <minecraft:concrete:6>,
    <minecraft:concrete:7>,
    <minecraft:concrete:8>,
    <minecraft:concrete:9>,
    <minecraft:concrete:10>,
    <minecraft:concrete:11>,
    <minecraft:concrete:12>,
    <minecraft:concrete:13>,
    <minecraft:concrete:14>,
    <minecraft:concrete:15>,
    <minecraft:concrete>,
    <minecraft:concrete_powder>,
    <minecraft:concrete_powder:1>,
    <minecraft:concrete_powder:2>,
    <minecraft:concrete_powder:3>,
    <minecraft:concrete_powder:4>,
    <minecraft:concrete_powder:5>,
    <minecraft:concrete_powder:6>,
    <minecraft:concrete_powder:7>,
    <minecraft:concrete_powder:8>,
    <minecraft:concrete_powder:9>,
    <minecraft:concrete_powder:10>,
    <minecraft:concrete_powder:11>,
    <minecraft:concrete_powder:12>,
    <minecraft:concrete_powder:13>,
    <minecraft:concrete_powder:14>,
    <minecraft:concrete_powder:15>,
/*
    <ancientwarfarenpc:shield_round_5>,
    <ancientwarfarenpc:shield_round_6>,
    <ancientwarfarenpc:shield_tribal_1>,
    <ancientwarfarenpc:shield_tribal_2>,
    <ancientwarfarevehicle:ammo_canister_shot_10>,
	*/
    <bibliocraft:clipboard>,
    <chisel:auto_chisel>,
    <cookingforblockheads:fridge>,
    <cookingforblockheads:heating_unit>,
    <cookingforblockheads:ice_unit>,
    <cookingforblockheads:kitchen_floor>,
    <cookingforblockheads:oven>,
    <cookingforblockheads:toaster>,
    <culinaryconstruct:sandwich_station>,
    <forestry:analyzer>,
    <forestry:arboretum>,
    <forestry:can>,
    <forestry:can:1>.withTag({Fluid: {FluidName: "water", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "lava", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "iron", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "gold", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "pigiron", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "cobalt", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ardite", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "manyullyn", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "knightslime", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "alubrass", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "brass", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "copper", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "tin", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "bronze", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "zinc", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "lead", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "nickel", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "silver", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "electrum", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "steel", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "aluminum", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidhydrogen", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidoxygen", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidchlorine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidsulfurdioxide", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidsulfurtrioxide", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "sulfuricacid", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidhydrogenchloride", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidethene", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidsodium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "brine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquiddeuterium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidtritium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidfusionfuel", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquidlithium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "heavywater", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "steam", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "peach_juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "pear_juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "persimmon_juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "peach_schnapps", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "perry", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "persimmon_wine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "sand", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "blood", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "poison", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "hot_spring_water", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "fierymetal", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "knightmetal", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "fiery_essence", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "slop", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk_holstein", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk_friesian", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk_jersey", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk_goat", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk_sheep", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "animania_honey", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "molten_neptunium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "molten_cheese", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "molten_cold_iron", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "creosote", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "plantoil", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ethanol", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "biodiesel", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "concrete", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "potion", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "uranium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "constantan", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "purified_water", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "bio.ethanol", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "biomass", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "glass", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "for.honey", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "seed.oil", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "short.mead", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "oliveoil", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ironberryjuice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "wildberryjuice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "grapejuice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "applejuice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "alewort", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ale", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "cider", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ironwine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "mead", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "wildberrywine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "wine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "oil", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "diesel", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "lubricant", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "napalm", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "dist_water", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "xpjuice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "cinderfire_wort", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "shimmerdew_wort", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "viscous_wort", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "cinderfire_whiskey", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "shimmerdew_spirits", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "viscous_brew", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "juniper_berry_juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "elderberry_juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "wormwood_mixture", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "sage_juice", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "gin", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "elderberry_wine", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "absinthe", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "sage_liqueur", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "titanium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "iridium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "platinum", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "invar", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "amethyst", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ruby", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "sapphire", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "peridot", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "osmium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "thaumium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "kovar", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "lavium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "qivium", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "chocolate_liquor", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "milk_chocolate", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "dark_chocolate", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "flux_goo", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "liquid_death", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "purifying_fluid", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "stone", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "obsidian", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "clay", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "dirt", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "emerald", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "blueslime", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "purpleslime", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "tannin", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "urushi", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "brine_netjry", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "waste", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "bitumen", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "bitumen_boiling", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "paraffin", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "magma_basaltic", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "ovis_atre_milk", Amount: 1000}}),
    <forestry:can:1>.withTag({Fluid: {FluidName: "smoke", Amount: 1000}}),
    <forestry:chipsets>.withTag({T: 0 as short}),
    <forestry:chipsets:1>.withTag({T: 1 as short}),
    <forestry:chipsets:2>.withTag({T: 2 as short}),
    <forestry:chipsets:3>.withTag({T: 3 as short}),
    <forestry:climatiser>,
    <forestry:crafting_material:4>,
    <forestry:crate>,
    <forestry:database>,
    <forestry:fabricator>,
    <forestry:farm_crops>,
    <forestry:farm_ender>,
    <forestry:farm_gourd>,
    <forestry:farm_mushroom>,
    <forestry:farm_nether>,
    <forestry:fermenter>,
    <forestry:ffarm>.withTag({FarmBlock: 0}),
    <forestry:ffarm>.withTag({FarmBlock: 1}),
    <forestry:ffarm>.withTag({FarmBlock: 2}),
    <forestry:ffarm>.withTag({FarmBlock: 3}),
    <forestry:ffarm>.withTag({FarmBlock: 4}),
    <forestry:ffarm>.withTag({FarmBlock: 5}),
    <forestry:ffarm>.withTag({FarmBlock: 6}),
    <forestry:ffarm>.withTag({FarmBlock: 7}),
    <forestry:ffarm>.withTag({FarmBlock: 8}),
    <forestry:ffarm>.withTag({FarmBlock: 9}),
    <forestry:ffarm>.withTag({FarmBlock: 10}),
    <forestry:ffarm:2>.withTag({FarmBlock: 0}),
    <forestry:ffarm:2>.withTag({FarmBlock: 1}),
    <forestry:ffarm:2>.withTag({FarmBlock: 2}),
    <forestry:ffarm:2>.withTag({FarmBlock: 3}),
    <forestry:ffarm:2>.withTag({FarmBlock: 4}),
    <forestry:ffarm:2>.withTag({FarmBlock: 5}),
    <forestry:ffarm:2>.withTag({FarmBlock: 6}),
    <forestry:ffarm:2>.withTag({FarmBlock: 7}),
    <forestry:ffarm:2>.withTag({FarmBlock: 8}),
    <forestry:ffarm:2>.withTag({FarmBlock: 9}),
    <forestry:ffarm:2>.withTag({FarmBlock: 10}),
    <forestry:ffarm:3>.withTag({FarmBlock: 0}),
    <forestry:ffarm:3>.withTag({FarmBlock: 1}),
    <forestry:ffarm:3>.withTag({FarmBlock: 2}),
    <forestry:ffarm:3>.withTag({FarmBlock: 3}),
    <forestry:ffarm:3>.withTag({FarmBlock: 4}),
    <forestry:ffarm:3>.withTag({FarmBlock: 5}),
    <forestry:ffarm:3>.withTag({FarmBlock: 6}),
    <forestry:ffarm:3>.withTag({FarmBlock: 7}),
    <forestry:ffarm:3>.withTag({FarmBlock: 8}),
    <forestry:ffarm:3>.withTag({FarmBlock: 9}),
    <forestry:ffarm:3>.withTag({FarmBlock: 10}),
    <forestry:ffarm:4>.withTag({FarmBlock: 0}),
    <forestry:ffarm:4>.withTag({FarmBlock: 1}),
    <forestry:ffarm:4>.withTag({FarmBlock: 2}),
    <forestry:ffarm:4>.withTag({FarmBlock: 3}),
    <forestry:ffarm:4>.withTag({FarmBlock: 4}),
    <forestry:ffarm:4>.withTag({FarmBlock: 5}),
    <forestry:ffarm:4>.withTag({FarmBlock: 6}),
    <forestry:ffarm:4>.withTag({FarmBlock: 7}),
    <forestry:ffarm:4>.withTag({FarmBlock: 8}),
    <forestry:ffarm:4>.withTag({FarmBlock: 9}),
    <forestry:ffarm:4>.withTag({FarmBlock: 10}),
    <forestry:ffarm:5>.withTag({FarmBlock: 0}),
    <forestry:ffarm:5>.withTag({FarmBlock: 1}),
    <forestry:ffarm:5>.withTag({FarmBlock: 2}),
    <forestry:ffarm:5>.withTag({FarmBlock: 3}),
    <forestry:ffarm:5>.withTag({FarmBlock: 4}),
    <forestry:ffarm:5>.withTag({FarmBlock: 5}),
    <forestry:ffarm:5>.withTag({FarmBlock: 6}),
    <forestry:ffarm:5>.withTag({FarmBlock: 7}),
    <forestry:ffarm:5>.withTag({FarmBlock: 8}),
    <forestry:ffarm:5>.withTag({FarmBlock: 9}),
    <forestry:ffarm:5>.withTag({FarmBlock: 10}),
    <forestry:flexible_casing>,
    <forestry:fluid.bio.ethanol>,
    <forestry:fluid.biomass>,
    <forestry:genetic_filter>,
    <forestry:habitat_former>,
    <forestry:habitat_screen>,
    <forestry:hardened_machine>,
    <forestry:iodine_capsule>,
    <forestry:mailbox>,
    <forestry:portable_alyzer>,
    <forestry:rainmaker>,
    <forestry:soldering_iron>,
    <forestry:stamps>,
    <forestry:stamps:1>,
    <forestry:stamps:2>,
    <forestry:stamps:3>,
    <forestry:stamps:4>,
    <forestry:stamps:5>,
    <forestry:stamps:6>,
    <forestry:still>,
    <forestry:thermionic_tubes>,
    <forestry:thermionic_tubes:1>,
    <forestry:thermionic_tubes:2>,
    <forestry:thermionic_tubes:4>,
    <forestry:thermionic_tubes:5>,
    <forestry:thermionic_tubes:6>,
    <forestry:thermionic_tubes:7>,
    <forestry:thermionic_tubes:9>,
    <forestry:thermionic_tubes:10>,
    <forestry:thermionic_tubes:11>,
    <forestry:thermionic_tubes:12>,
    <forestry:trade_station>,

	<fossil:analyzer>,
	<fossil:bubble_blower>,
	<fossil:cultivate>,
	<fossil:alligator_gar_dna>,
	<fossil:allosaurus_dna>,
	<fossil:ankylosaurus_dna>,
	<fossil:arthropleura_dna>,
	<fossil:brachiosaurus_dna>,
	<fossil:ceratosaurus_dna>,
	<fossil:chicken_dna>,
	<fossil:citipati_dna>,
	<fossil:coelacanth_dna>,
	<fossil:compsognathus_dna>,
	<fossil:confuciusornis_dna>,
	<fossil:cow_dna>,
	<fossil:cow_syringe>,
	<fossil:crassigyrinus_dna>,
	<fossil:deinonychus_dna>,
	<fossil:dilophosaurus_dna>,
	<fossil:diplocaulus_dna>,
	<fossil:diplodocus_dna>,
	<fossil:dodo_dna>,
	<fossil:donkey_dna>,
	<fossil:donkey_syringe>,
	<fossil:dryosaurus_dna>,
	<fossil:edaphosaurus_dna>,
	<fossil:elasmotherium_dna>,
	<fossil:elasmotherium_syringe>,
	<fossil:gallimimus_dna>,
	<fossil:gastornis_dna>,
	<fossil:henodus_dna>,
	<fossil:horse_dna>,
	<fossil:horse_syringe>,
	<fossil:icthyosaurus_dna>,
	<fossil:kelenken_dna>,
	<fossil:liopleurodon_dna>,
	<fossil:llama_dna>,
	<fossil:llama_syringe>,
	<fossil:mammoth_dna>,
	<fossil:mammoth_syringe>,
	<fossil:megalania_dna>,
	<fossil:megaloceros_dna>,
	<fossil:megaloceros_syringe>,
	<fossil:megalodon_dna>,
	<fossil:megalograptus_dna>,
	<fossil:meganeura_dna>,
	<fossil:mosasaurus_dna>,
	<fossil:nautilus_dna>,
	<fossil:ornitholestes_dna>,
	<fossil:pachycephalosaurus_dna>,
	<fossil:parasaurolophus_dna>,
	<fossil:parrot_dna>,
	<fossil:phorusrhacos_dna>,
	<fossil:pig_dna>,
	<fossil:pig_syringe>,
	<fossil:platybelodon_dna>,
	<fossil:platybelodon_syringe>,
	<fossil:plesiosaur_dna>,
	<fossil:polarbear_dna>,
	<fossil:polarbear_syringe>,
	<fossil:pterosaur_dna>,
	<fossil:quagga_dna>,
	<fossil:quagga_syringe>,
	<fossil:rabbit_dna>,
	<fossil:rabbit_syringe>,
	<fossil:sarcosuchus_dna>,
	<fossil:sheep_dna>,
	<fossil:sheep_syringe>,
	<fossil:smilodon_dna>,
	<fossil:smilodon_syringe>,
	<fossil:spinosaurus_dna>,
	<fossil:stegosaurus_dna>,
	<fossil:sturgeon_dna>,
	<fossil:therizinosaurus_dna>,
	<fossil:tiktaalik_dna>,
	<fossil:titanis_dna>,
	<fossil:triceratops_dna>,
	<fossil:tyrannosaurus_dna>,
	<fossil:velociraptor_dna>,
	<fossil:bio_goo>,
	<fossil:chicken_essence>,
	<fossil:stunted_essence>,

    <grapplemod:repeller>,
    <grapplemod:rocketdoublemotorhook>,
    <grapplemod:rockethook>,
    <grapplemod:rocketupgradeitem>,
    <grapplemod:smarthook>,
    <immersivepetroleum:dummy>,
    <immersivepetroleum:material>,
    <immersivepetroleum:metal_device>,
    <immersivepetroleum:metal_device:1>,
    <immersivepetroleum:metal_multiblock>,
    <immersivepetroleum:oil_can>,
    <immersivepetroleum:schematic>,
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:CokeOven"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:AlloySmelter"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:BlastFurnace"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:BlastFurnaceAdvanced"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:MetalPress"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Crusher"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:SheetmetalTank"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Silo"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Assembler"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:AutoWorkbench"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:BottlingMachine"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Squeezer"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Fermenter"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Refinery"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:DieselGenerator"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:ArcFurnace"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Lightningrod"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Mixer"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:Feedthrough"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IP:DistillationTower"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IP:Pumpjack"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:Distiller"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:SolarTower"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:SolarReflector"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:SteamTurbine"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:Boiler"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:Alternator"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IT:CokeOvenAdvanced"}),
    <immersivepetroleum:schematic>.withTag({multiblock: "IE:ExcavatorDemo", flip: 1 as byte}),
    <immersivepetroleum:speedboat>,
    <immersivepetroleum:stone_decoration>,
    <immersivepetroleum:upgrades>,
    <immersivepetroleum:upgrades:1>,
    <immersivepetroleum:upgrades:2>,
    <immersivepetroleum:upgrades:3>,
    <immersivepetroleum:upgrades:4>,
    <malisisdoors:garage_door>,
    <malisisdoors:iron_sliding_door>,
    <malisisdoors:laboratory_door>,
    <malisisdoors:rustyhandle>,
    <malisisdoors:rustyhatch>,
    <malisisdoors:rustyladder>,
    <malisisdoors:sliding_trapdoor>,
    <mcwbridges:most1>,
    <mcwbridges:most2>,
    /*
    <mekanism:basicblock>,
    <mekanism:basicblock:2>,
    <mekanism:basicblock:4>,
    <mekanism:basicblock:5>,
    <mekanism:basicblock:6>.withTag({tier: 0}),
    <mekanism:basicblock:6>.withTag({tier: 1}),
    <mekanism:basicblock:6>.withTag({tier: 2}),
    <mekanism:basicblock:6>.withTag({tier: 3}),
    <mekanism:basicblock:6>.withTag({tier: 4}),
    <mekanism:basicblock:7>,
    <mekanism:basicblock:8>,
    <mekanism:basicblock:9>,
    <mekanism:basicblock:10>,
    <mekanism:basicblock:11>,
    <mekanism:basicblock:12>,
    <mekanism:basicblock:14>,
    <mekanism:basicblock:15>,
    <mekanism:basicblock2>,
    <mekanism:basicblock2:1>,
    <mekanism:basicblock2:2>,
    <mekanism:basicblock2:3>.withTag({tier: 0}),
    <mekanism:basicblock2:3>.withTag({tier: 1}),
    <mekanism:basicblock2:3>.withTag({tier: 2}),
    <mekanism:basicblock2:3>.withTag({tier: 3}),
    <mekanism:basicblock2:4>.withTag({tier: 0}),
    <mekanism:basicblock2:4>.withTag({tier: 1}),
    <mekanism:basicblock2:4>.withTag({tier: 2}),
    <mekanism:basicblock2:4>.withTag({tier: 3}),
    <mekanism:basicblock2:5>,
    <mekanism:basicblock2:6>,
    <mekanism:basicblock2:7>,
    <mekanism:basicblock2:8>,
    <mekanism:basicblock2:9>,
    */
    <mekanism:biofuel>,
    <mekanism:boundingblock>,
    <mekanism:cardboardbox>,
    <mekanism:clump>,
    <mekanism:clump:1>,
    <mekanism:clump:2>,
    <mekanism:clump:3>,
    <mekanism:clump:4>,
    <mekanism:clump:5>,
    <mekanism:clump:6>,
    <mekanism:compressedcarbon>,
    <mekanism:compresseddiamond>,
    <mekanism:compressedobsidian>,
    <mekanism:compressedredstone>,
    <mekanism:configurationcard>,
    <mekanism:configurator>,
    <mekanism:configurator>.withTag({mekData: {energyStored: 60000.0}}),
    <mekanism:controlcircuit>,
    <mekanism:controlcircuit:1>,
    <mekanism:controlcircuit:2>,
    <mekanism:controlcircuit:3>,
    <mekanism:craftingformula>,
    <mekanism:crystal>,
    <mekanism:crystal:1>,
    <mekanism:crystal:2>,
    <mekanism:crystal:3>,
    <mekanism:crystal:4>,
    <mekanism:crystal:5>,
    <mekanism:crystal:6>,
    <mekanism:dictionary>,
    /*
    <mekanism:dirtydust>,
    <mekanism:dirtydust:1>,
    <mekanism:dirtydust:2>,
    <mekanism:dirtydust:3>,
    <mekanism:dirtydust:4>,
    <mekanism:dirtydust:5>,
    <mekanism:dirtydust:6>,
    <mekanism:dust>,
    <mekanism:dust:1>,
    <mekanism:dust:2>,
    <mekanism:dust:3>,
    <mekanism:dust:5>,
    <mekanism:dust:6>,
    */
    <mekanism:electricbow>,
    <mekanism:electricbow>.withTag({mekData: {energyStored: 120000.0}}),
    <mekanism:electrolyticcore>,
    <mekanism:energycube>.withTag({tier: 0}),
    <mekanism:energycube>.withTag({tier: 0, mekData: {energyStored: 2000000.0}}),
    <mekanism:energycube>.withTag({tier: 1}),
    <mekanism:energycube>.withTag({tier: 1, mekData: {energyStored: 8000000.0}}),
    <mekanism:energycube>.withTag({tier: 2}),
    <mekanism:energycube>.withTag({tier: 2, mekData: {energyStored: 3.2E7}}),
    <mekanism:energycube>.withTag({tier: 3}),
    <mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}}),
    <mekanism:energycube>.withTag({tier: 4}),
    <mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}),
    <mekanism:energytablet>,
    <mekanism:energytablet>.withTag({mekData: {energyStored: 1000000.0}}),
    <mekanism:energyupgrade>,
    <mekanism:enrichedalloy>,
    <mekanism:enrichediron>,
    <mekanism:filterupgrade>,
    <mekanism:flamethrower>,
    <mekanism:flamethrower>.withTag({mekData: {stored: {amount: 24000, gasName: "hydrogen"}}}),
    <mekanism:freerunners>,
    <mekanism:freerunners>.withTag({mekData: {energyStored: 64000.0}}),
    <mekanism:gasmask>,
    <mekanism:gastank>.withTag({tier: 0}),
    <mekanism:gastank>.withTag({tier: 1}),
    <mekanism:gastank>.withTag({tier: 2}),
    <mekanism:gastank>.withTag({tier: 3}),
    <mekanism:gastank>.withTag({tier: 4}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogen"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "oxygen"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "water"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "chlorine"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurdioxide"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurtrioxide"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfuricacid"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogenchloride"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "ethene"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sodium"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "brine"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "deuterium"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "tritium"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "fusionfuel"}}}),
    <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "lithium"}}}),
    <mekanism:gasupgrade>,
    <mekanism:gaugedropper>,
    <mekanism:glowpanel>,
    <mekanism:glowpanel:1>,
    <mekanism:glowpanel:2>,
    <mekanism:glowpanel:3>,
    <mekanism:glowpanel:4>,
    <mekanism:glowpanel:5>,
    <mekanism:glowpanel:6>,
    <mekanism:glowpanel:7>,
    <mekanism:glowpanel:8>,
    <mekanism:glowpanel:9>,
    <mekanism:glowpanel:10>,
    <mekanism:glowpanel:11>,
    <mekanism:glowpanel:12>,
    <mekanism:glowpanel:13>,
    <mekanism:glowpanel:14>,
    <mekanism:glowpanel:15>,
    <mekanism:glowplasticblock>,
    <mekanism:glowplasticblock:1>,
    <mekanism:glowplasticblock:2>,
    <mekanism:glowplasticblock:3>,
    <mekanism:glowplasticblock:4>,
    <mekanism:glowplasticblock:5>,
    <mekanism:glowplasticblock:6>,
    <mekanism:glowplasticblock:7>,
    <mekanism:glowplasticblock:8>,
    <mekanism:glowplasticblock:9>,
    <mekanism:glowplasticblock:10>,
    <mekanism:glowplasticblock:11>,
    <mekanism:glowplasticblock:12>,
    <mekanism:glowplasticblock:13>,
    <mekanism:glowplasticblock:14>,
    <mekanism:glowplasticblock:15>,
    /*
    <mekanism:ingot>,
    <mekanism:ingot:1>,
    <mekanism:ingot:3>,
    <mekanism:ingot:4>,
    <mekanism:ingot:5>,
    */
    <mekanism:itemproxy>,
    <mekanism:machineblock>,
    <mekanism:machineblock:1>,
    <mekanism:machineblock:2>,
    <mekanism:machineblock:3>,
    <mekanism:machineblock:4>,
    <mekanism:machineblock:5>.withTag({recipeType: 0}),
    <mekanism:machineblock:5>.withTag({recipeType: 1}),
    <mekanism:machineblock:5>.withTag({recipeType: 2}),
    <mekanism:machineblock:5>.withTag({recipeType: 3}),
    <mekanism:machineblock:5>.withTag({recipeType: 4}),
    <mekanism:machineblock:5>.withTag({recipeType: 5}),
    <mekanism:machineblock:5>.withTag({recipeType: 6}),
    <mekanism:machineblock:5>.withTag({recipeType: 7}),
    <mekanism:machineblock:5>.withTag({recipeType: 8}),
    <mekanism:machineblock:6>.withTag({recipeType: 0}),
    <mekanism:machineblock:6>.withTag({recipeType: 1}),
    <mekanism:machineblock:6>.withTag({recipeType: 2}),
    <mekanism:machineblock:6>.withTag({recipeType: 3}),
    <mekanism:machineblock:6>.withTag({recipeType: 4}),
    <mekanism:machineblock:6>.withTag({recipeType: 5}),
    <mekanism:machineblock:6>.withTag({recipeType: 6}),
    <mekanism:machineblock:6>.withTag({recipeType: 7}),
    <mekanism:machineblock:6>.withTag({recipeType: 8}),
    <mekanism:machineblock:7>.withTag({recipeType: 0}),
    <mekanism:machineblock:7>.withTag({recipeType: 1}),
    <mekanism:machineblock:7>.withTag({recipeType: 2}),
    <mekanism:machineblock:7>.withTag({recipeType: 3}),
    <mekanism:machineblock:7>.withTag({recipeType: 4}),
    <mekanism:machineblock:7>.withTag({recipeType: 5}),
    <mekanism:machineblock:7>.withTag({recipeType: 6}),
    <mekanism:machineblock:7>.withTag({recipeType: 7}),
    <mekanism:machineblock:7>.withTag({recipeType: 8}),
    <mekanism:machineblock:8>,
    <mekanism:machineblock:9>,
    <mekanism:machineblock:10>,
    <mekanism:machineblock:11>,
    <mekanism:machineblock:12>,
    <mekanism:machineblock:13>,
    <mekanism:machineblock:14>,
    <mekanism:machineblock:15>,
    <mekanism:machineblock2>,
    <mekanism:machineblock2:1>,
    <mekanism:machineblock2:2>,
    <mekanism:machineblock2:3>,
    <mekanism:machineblock2:4>,
    <mekanism:machineblock2:5>,
    <mekanism:machineblock2:6>,
    <mekanism:machineblock2:7>,
    <mekanism:machineblock2:8>,
    <mekanism:machineblock2:9>,
    <mekanism:machineblock2:10>,
    <mekanism:machineblock2:11>.withTag({tier: 0}),
    <mekanism:machineblock2:11>.withTag({tier: 1}),
    <mekanism:machineblock2:11>.withTag({tier: 2}),
    <mekanism:machineblock2:11>.withTag({tier: 3}),
    <mekanism:machineblock2:11>.withTag({tier: 4}),
    <mekanism:machineblock2:12>,
    <mekanism:machineblock2:13>,
    <mekanism:machineblock2:14>,
    <mekanism:machineblock2:15>,
    <mekanism:machineblock3>,
    <mekanism:machineblock3:1>,
    <mekanism:machineblock3:3>,
    <mekanism:machineblock3:4>,
    <mekanism:machineblock3:5>,
    <mekanism:machineblock3:6>,
    <mekanism:mufflingupgrade>,
    <mekanism:networkreader>,
    <mekanism:networkreader>.withTag({mekData: {energyStored: 60000.0}}),
    /*
    <mekanism:nugget>,
    <mekanism:nugget:1>,
    <mekanism:nugget:3>,
    <mekanism:nugget:4>,
    <mekanism:nugget:5>,
    */
    <mekanism:obsidiantnt>,
    /*
    <mekanism:otherdust>,
    <mekanism:otherdust:1>,
    <mekanism:otherdust:3>,
    <mekanism:otherdust:4>,
    <mekanism:otherdust:5>,
    <mekanism:otherdust:6>,
    */
    <mekanism:plasticblock>,
    <mekanism:plasticblock:1>,
    <mekanism:plasticblock:2>,
    <mekanism:plasticblock:3>,
    <mekanism:plasticblock:4>,
    <mekanism:plasticblock:5>,
    <mekanism:plasticblock:6>,
    <mekanism:plasticblock:7>,
    <mekanism:plasticblock:8>,
    <mekanism:plasticblock:9>,
    <mekanism:plasticblock:10>,
    <mekanism:plasticblock:11>,
    <mekanism:plasticblock:12>,
    <mekanism:plasticblock:13>,
    <mekanism:plasticblock:14>,
    <mekanism:plasticblock:15>,
    <mekanism:plasticfence>,
    <mekanism:plasticfence:1>,
    <mekanism:plasticfence:2>,
    <mekanism:plasticfence:3>,
    <mekanism:plasticfence:4>,
    <mekanism:plasticfence:5>,
    <mekanism:plasticfence:6>,
    <mekanism:plasticfence:7>,
    <mekanism:plasticfence:8>,
    <mekanism:plasticfence:9>,
    <mekanism:plasticfence:10>,
    <mekanism:plasticfence:11>,
    <mekanism:plasticfence:12>,
    <mekanism:plasticfence:13>,
    <mekanism:plasticfence:14>,
    <mekanism:plasticfence:15>,
    <mekanism:polyethene>,
    <mekanism:polyethene:1>,
    <mekanism:polyethene:2>,
    <mekanism:polyethene:3>,
    <mekanism:portableteleporter>,
    <mekanism:portableteleporter>.withTag({mekData: {energyStored: 1000000.0}}),
    <mekanism:reinforcedalloy>,
    <mekanism:reinforcedplasticblock>,
    <mekanism:reinforcedplasticblock:1>,
    <mekanism:reinforcedplasticblock:2>,
    <mekanism:reinforcedplasticblock:3>,
    <mekanism:reinforcedplasticblock:4>,
    <mekanism:reinforcedplasticblock:5>,
    <mekanism:reinforcedplasticblock:6>,
    <mekanism:reinforcedplasticblock:7>,
    <mekanism:reinforcedplasticblock:8>,
    <mekanism:reinforcedplasticblock:9>,
    <mekanism:reinforcedplasticblock:10>,
    <mekanism:reinforcedplasticblock:11>,
    <mekanism:reinforcedplasticblock:12>,
    <mekanism:reinforcedplasticblock:13>,
    <mekanism:reinforcedplasticblock:14>,
    <mekanism:reinforcedplasticblock:15>,
    <mekanism:roadplasticblock>,
    <mekanism:roadplasticblock:1>,
    <mekanism:roadplasticblock:2>,
    <mekanism:roadplasticblock:3>,
    <mekanism:roadplasticblock:4>,
    <mekanism:roadplasticblock:5>,
    <mekanism:roadplasticblock:6>,
    <mekanism:roadplasticblock:7>,
    <mekanism:roadplasticblock:8>,
    <mekanism:roadplasticblock:9>,
    <mekanism:roadplasticblock:10>,
    <mekanism:roadplasticblock:11>,
    <mekanism:roadplasticblock:12>,
    <mekanism:roadplasticblock:13>,
    <mekanism:roadplasticblock:14>,
    <mekanism:roadplasticblock:15>,
    <mekanism:robit>,
    <mekanism:robit>.withTag({mekData: {energyStored: 100000.0}}),
    <mekanism:salt>,
    <mekanism:saltblock>,
    <mekanism:sawdust>,
    <mekanism:scubatank>,
    <mekanism:scubatank>.withTag({mekData: {stored: {amount: 24000, gasName: "oxygen"}}}),
    <mekanism:seismicreader>,
    <mekanism:seismicreader>.withTag({mekData: {energyStored: 12000.0}}),
    <mekanism:shard>,
    <mekanism:shard:1>,
    <mekanism:shard:2>,
    <mekanism:shard:3>,
    <mekanism:shard:4>,
    <mekanism:shard:5>,
    <mekanism:shard:6>,
    <mekanism:slickplasticblock>,
    <mekanism:slickplasticblock:1>,
    <mekanism:slickplasticblock:2>,
    <mekanism:slickplasticblock:3>,
    <mekanism:slickplasticblock:4>,
    <mekanism:slickplasticblock:5>,
    <mekanism:slickplasticblock:6>,
    <mekanism:slickplasticblock:7>,
    <mekanism:slickplasticblock:8>,
    <mekanism:slickplasticblock:9>,
    <mekanism:slickplasticblock:10>,
    <mekanism:slickplasticblock:11>,
    <mekanism:slickplasticblock:12>,
    <mekanism:slickplasticblock:13>,
    <mekanism:slickplasticblock:14>,
    <mekanism:slickplasticblock:15>,
    <mekanism:speedupgrade>,
    <mekanism:substrate>,
    <mekanism:teleportationcore>,
    <mekanism:tierinstaller>,
    <mekanism:tierinstaller:1>,
    <mekanism:tierinstaller:2>,
    <mekanism:tierinstaller:3>,
    <mekanism:transmitter>.withTag({tier: 0}),
    <mekanism:transmitter>.withTag({tier: 1}),
    <mekanism:transmitter>.withTag({tier: 2}),
    <mekanism:transmitter>.withTag({tier: 3}),
    <mekanism:transmitter:1>.withTag({tier: 0}),
    <mekanism:transmitter:1>.withTag({tier: 1}),
    <mekanism:transmitter:1>.withTag({tier: 2}),
    <mekanism:transmitter:1>.withTag({tier: 3}),
    <mekanism:transmitter:2>.withTag({tier: 0}),
    <mekanism:transmitter:2>.withTag({tier: 1}),
    <mekanism:transmitter:2>.withTag({tier: 2}),
    <mekanism:transmitter:2>.withTag({tier: 3}),
    <mekanism:transmitter:3>.withTag({tier: 0}),
    <mekanism:transmitter:3>.withTag({tier: 1}),
    <mekanism:transmitter:3>.withTag({tier: 2}),
    <mekanism:transmitter:3>.withTag({tier: 3}),
    <mekanism:transmitter:4>.withTag({tier: 0}),
    <mekanism:transmitter:5>.withTag({tier: 0}),
    <mekanism:transmitter:6>.withTag({tier: 0}),
    <mekanism:transmitter:6>.withTag({tier: 1}),
    <mekanism:transmitter:6>.withTag({tier: 2}),
    <mekanism:transmitter:6>.withTag({tier: 3}),
    <mekanism:walkietalkie>,
    <tcomplement:materials:6>,
    <tconstruct:clear_glass>,
    <tconstruct:clear_stained_glass>,
    <tconstruct:clear_stained_glass:1>,
    <tconstruct:clear_stained_glass:2>,
    <tconstruct:clear_stained_glass:3>,
    <tconstruct:clear_stained_glass:4>,
    <tconstruct:clear_stained_glass:5>,
    <tconstruct:clear_stained_glass:6>,
    <tconstruct:clear_stained_glass:7>,
    <tconstruct:clear_stained_glass:8>,
    <tconstruct:clear_stained_glass:9>,
    <tconstruct:clear_stained_glass:10>,
    <tconstruct:clear_stained_glass:11>,
    <tconstruct:clear_stained_glass:12>,
    <tconstruct:clear_stained_glass:13>,
    <tconstruct:clear_stained_glass:14>,
    <tconstruct:clear_stained_glass:15>,
    <toughasnails:temperature_coil>,
    <toughasnails:temperature_coil:1>,
    <immersivepetroleum:dummy>,
	<immersivepetroleum:material>,
	<immersivepetroleum:metal_device>,
	<immersivepetroleum:metal_device:1>,
	<immersivepetroleum:metal_multiblock>,
	<immersivepetroleum:oil_can>,
	<immersivepetroleum:schematic>,
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:CokeOven"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:AlloySmelter"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:BlastFurnace"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:BlastFurnaceAdvanced"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:MetalPress"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Crusher"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:SheetmetalTank"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Silo"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Assembler"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:AutoWorkbench"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:BottlingMachine"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Squeezer"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Fermenter"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Refinery"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:DieselGenerator"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:ArcFurnace"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Lightningrod"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Mixer"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:Feedthrough"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IP:DistillationTower"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IP:Pumpjack"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:Distiller"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:SolarTower"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:SolarReflector"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:SteamTurbine"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:Boiler"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:Alternator"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IT:CokeOvenAdvanced"}),
	<immersivepetroleum:schematic>.withTag({multiblock: "IE:ExcavatorDemo", flip: 1 as byte}),
	<immersivepetroleum:speedboat>,
	<immersivepetroleum:stone_decoration>,
	<immersivepetroleum:upgrades>,
	<immersivepetroleum:upgrades:1>,
	<immersivepetroleum:upgrades:2>,
	<immersivepetroleum:upgrades:3>,
	<immersivepetroleum:upgrades:4>,
	<mekanism:basicblock:6>.withTag({tier: 0}),
	<mekanism:basicblock:6>.withTag({tier: 1}),
	<mekanism:basicblock:6>.withTag({tier: 2}),
	<mekanism:basicblock:6>.withTag({tier: 3}),
	<mekanism:basicblock:6>.withTag({tier: 4}),
	<mekanism:basicblock:7>,
	<mekanism:basicblock:8>,
	<mekanism:basicblock:9>,
	<mekanism:basicblock:10>,
	<mekanism:basicblock:11>,
	<mekanism:basicblock:12>,
	<mekanism:basicblock:14>,
	<mekanism:basicblock:15>,
	<mekanism:basicblock2>,
	<mekanism:basicblock2:1>,
	<mekanism:basicblock2:2>,
	<mekanism:basicblock2:3>.withTag({tier: 0}),
	<mekanism:basicblock2:3>.withTag({tier: 1}),
	<mekanism:basicblock2:3>.withTag({tier: 2}),
	<mekanism:basicblock2:3>.withTag({tier: 3}),
	<mekanism:basicblock2:4>.withTag({tier: 0}),
	<mekanism:basicblock2:4>.withTag({tier: 1}),
	<mekanism:basicblock2:4>.withTag({tier: 2}),
	<mekanism:basicblock2:4>.withTag({tier: 3}),
	<mekanism:basicblock2:5>,
	<mekanism:basicblock2:6>,
	<mekanism:basicblock2:7>,
	<mekanism:basicblock2:8>,
	<mekanism:basicblock2:9>,
	<mekanism:biofuel>,
	<mekanism:boundingblock>,
	<mekanism:cardboardbox>,
	<mekanism:clump>,
	<mekanism:clump:1>,
	<mekanism:clump:2>,
	<mekanism:clump:3>,
	<mekanism:clump:4>,
	<mekanism:clump:5>,
	<mekanism:clump:6>,
	<mekanism:compressedcarbon>,
	<mekanism:compresseddiamond>,
	<mekanism:compressedobsidian>,
	<mekanism:compressedredstone>,
	<mekanism:configurationcard>,
	<mekanism:configurator>,
	<mekanism:configurator>.withTag({mekData: {energyStored: 60000.0}}),
	<mekanism:controlcircuit>,
	<mekanism:controlcircuit:1>,
	<mekanism:controlcircuit:2>,
	<mekanism:controlcircuit:3>,
	<mekanism:craftingformula>,
	<mekanism:crystal>,
	<mekanism:crystal:1>,
	<mekanism:crystal:2>,
	<mekanism:crystal:3>,
	<mekanism:crystal:4>,
	<mekanism:crystal:5>,
	<mekanism:crystal:6>,
	<mekanism:dictionary>,
	<mekanism:electricbow>,
	<mekanism:electricbow>.withTag({mekData: {energyStored: 120000.0}}),
	<mekanism:electrolyticcore>,
	<mekanism:energycube>.withTag({tier: 0}),
	<mekanism:energycube>.withTag({tier: 0, mekData: {energyStored: 2000000.0}}),
	<mekanism:energycube>.withTag({tier: 1}),
	<mekanism:energycube>.withTag({tier: 1, mekData: {energyStored: 8000000.0}}),
	<mekanism:energycube>.withTag({tier: 2}),
	<mekanism:energycube>.withTag({tier: 2, mekData: {energyStored: 3.2E7}}),
	<mekanism:energycube>.withTag({tier: 3}),
	<mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}}),
	<mekanism:energycube>.withTag({tier: 4}),
	<mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}),
	<mekanism:energytablet>,
	<mekanism:energytablet>.withTag({mekData: {energyStored: 1000000.0}}),
	<mekanism:energyupgrade>,
	<mekanism:enrichedalloy>,
	<mekanism:enrichediron>,
	<mekanism:filterupgrade>,
	<mekanism:flamethrower>,
	<mekanism:flamethrower>.withTag({mekData: {stored: {amount: 24000, gasName: "hydrogen"}}}),
	<mekanism:freerunners>,
	<mekanism:freerunners>.withTag({mekData: {energyStored: 64000.0}}),
	<mekanism:gasmask>,
	<mekanism:gastank>.withTag({tier: 0}),
	<mekanism:gastank>.withTag({tier: 1}),
	<mekanism:gastank>.withTag({tier: 2}),
	<mekanism:gastank>.withTag({tier: 3}),
	<mekanism:gastank>.withTag({tier: 4}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogen"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "oxygen"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "water"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "chlorine"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurdioxide"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurtrioxide"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfuricacid"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogenchloride"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "ethene"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sodium"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "brine"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "deuterium"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "tritium"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "fusionfuel"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "lithium"}}}),
	<mekanism:gasupgrade>,
	<mekanism:gaugedropper>,
	<mekanism:glowpanel>,
	<mekanism:glowpanel:1>,
	<mekanism:glowpanel:2>,
	<mekanism:glowpanel:3>,
	<mekanism:glowpanel:4>,
	<mekanism:glowpanel:5>,
	<mekanism:glowpanel:6>,
	<mekanism:glowpanel:7>,
	<mekanism:glowpanel:8>,
	<mekanism:glowpanel:9>,
	<mekanism:glowpanel:10>,
	<mekanism:glowpanel:11>,
	<mekanism:glowpanel:12>,
	<mekanism:glowpanel:13>,
	<mekanism:glowpanel:14>,
	<mekanism:glowpanel:15>,
	<mekanism:glowplasticblock>,
	<mekanism:glowplasticblock:1>,
	<mekanism:glowplasticblock:2>,
	<mekanism:glowplasticblock:3>,
	<mekanism:glowplasticblock:4>,
	<mekanism:glowplasticblock:5>,
	<mekanism:glowplasticblock:6>,
	<mekanism:glowplasticblock:7>,
	<mekanism:glowplasticblock:8>,
	<mekanism:glowplasticblock:9>,
	<mekanism:glowplasticblock:10>,
	<mekanism:glowplasticblock:11>,
	<mekanism:glowplasticblock:12>,
	<mekanism:glowplasticblock:13>,
	<mekanism:glowplasticblock:14>,
	<mekanism:glowplasticblock:15>,
	<mekanism:itemproxy>,
	<mekanism:machineblock>,
	<mekanism:machineblock:1>,
	<mekanism:machineblock:2>,
	<mekanism:machineblock:3>,
	<mekanism:machineblock:4>,
	<mekanism:machineblock:5>.withTag({recipeType: 0}),
	<mekanism:machineblock:5>.withTag({recipeType: 1}),
	<mekanism:machineblock:5>.withTag({recipeType: 2}),
	<mekanism:machineblock:5>.withTag({recipeType: 3}),
	<mekanism:machineblock:5>.withTag({recipeType: 4}),
	<mekanism:machineblock:5>.withTag({recipeType: 5}),
	<mekanism:machineblock:5>.withTag({recipeType: 6}),
	<mekanism:machineblock:5>.withTag({recipeType: 7}),
	<mekanism:machineblock:5>.withTag({recipeType: 8}),
	<mekanism:machineblock:6>.withTag({recipeType: 0}),
	<mekanism:machineblock:6>.withTag({recipeType: 1}),
	<mekanism:machineblock:6>.withTag({recipeType: 2}),
	<mekanism:machineblock:6>.withTag({recipeType: 3}),
	<mekanism:machineblock:6>.withTag({recipeType: 4}),
	<mekanism:machineblock:6>.withTag({recipeType: 5}),
	<mekanism:machineblock:6>.withTag({recipeType: 6}),
	<mekanism:machineblock:6>.withTag({recipeType: 7}),
	<mekanism:machineblock:6>.withTag({recipeType: 8}),
	<mekanism:machineblock:7>.withTag({recipeType: 0}),
	<mekanism:machineblock:7>.withTag({recipeType: 1}),
	<mekanism:machineblock:7>.withTag({recipeType: 2}),
	<mekanism:machineblock:7>.withTag({recipeType: 3}),
	<mekanism:machineblock:7>.withTag({recipeType: 4}),
	<mekanism:machineblock:7>.withTag({recipeType: 5}),
	<mekanism:machineblock:7>.withTag({recipeType: 6}),
	<mekanism:machineblock:7>.withTag({recipeType: 7}),
	<mekanism:machineblock:7>.withTag({recipeType: 8}),
	<mekanism:machineblock:8>,
	<mekanism:machineblock:9>,
	<mekanism:machineblock:10>,
	<mekanism:machineblock:11>,
	<mekanism:machineblock:12>,
	<mekanism:machineblock:13>,
	<mekanism:machineblock:14>,
	<mekanism:machineblock:15>,
	<mekanism:machineblock2>,
	<mekanism:machineblock2:1>,
	<mekanism:machineblock2:2>,
	<mekanism:machineblock2:3>,
	<mekanism:machineblock2:4>,
	<mekanism:machineblock2:5>,
	<mekanism:machineblock2:6>,
	<mekanism:machineblock2:7>,
	<mekanism:machineblock2:8>,
	<mekanism:machineblock2:9>,
	<mekanism:machineblock2:10>,
	<mekanism:machineblock2:11>.withTag({tier: 0}),
	<mekanism:machineblock2:11>.withTag({tier: 1}),
	<mekanism:machineblock2:11>.withTag({tier: 2}),
	<mekanism:machineblock2:11>.withTag({tier: 3}),
	<mekanism:machineblock2:11>.withTag({tier: 4}),
	<mekanism:machineblock2:12>,
	<mekanism:machineblock2:13>,
	<mekanism:machineblock2:14>,
	<mekanism:machineblock2:15>,
	<mekanism:machineblock3>,
	<mekanism:machineblock3:1>,
	<mekanism:machineblock3:3>,
	<mekanism:machineblock3:4>,
	<mekanism:machineblock3:5>,
	<mekanism:machineblock3:6>,
	<mekanism:mufflingupgrade>,
	<mekanism:networkreader>,
	<mekanism:networkreader>.withTag({mekData: {energyStored: 60000.0}}),
	<mekanism:obsidiantnt>,
	<mekanism:otherdust>,
	<mekanism:otherdust:1>,
	<mekanism:otherdust:3>,
	<mekanism:otherdust:4>,
	<mekanism:otherdust:5>,
	<mekanism:otherdust:6>,
	<mekanism:plasticblock>,
	<mekanism:plasticblock:1>,
	<mekanism:plasticblock:2>,
	<mekanism:plasticblock:3>,
	<mekanism:plasticblock:4>,
	<mekanism:plasticblock:5>,
	<mekanism:plasticblock:6>,
	<mekanism:plasticblock:7>,
	<mekanism:plasticblock:8>,
	<mekanism:plasticblock:9>,
	<mekanism:plasticblock:10>,
	<mekanism:plasticblock:11>,
	<mekanism:plasticblock:12>,
	<mekanism:plasticblock:13>,
	<mekanism:plasticblock:14>,
	<mekanism:plasticblock:15>,
	<mekanism:plasticfence>,
	<mekanism:plasticfence:1>,
	<mekanism:plasticfence:2>,
	<mekanism:plasticfence:3>,
	<mekanism:plasticfence:4>,
	<mekanism:plasticfence:5>,
	<mekanism:plasticfence:6>,
	<mekanism:plasticfence:7>,
	<mekanism:plasticfence:8>,
	<mekanism:plasticfence:9>,
	<mekanism:plasticfence:10>,
	<mekanism:plasticfence:11>,
	<mekanism:plasticfence:12>,
	<mekanism:plasticfence:13>,
	<mekanism:plasticfence:14>,
	<mekanism:plasticfence:15>,
	<mekanism:polyethene>,
	<mekanism:polyethene:1>,
	<mekanism:polyethene:2>,
	<mekanism:polyethene:3>,
	<mekanism:portableteleporter>,
	<mekanism:portableteleporter>.withTag({mekData: {energyStored: 1000000.0}}),
	<mekanism:reinforcedalloy>,
	<mekanism:reinforcedplasticblock>,
	<mekanism:reinforcedplasticblock:1>,
	<mekanism:reinforcedplasticblock:2>,
	<mekanism:reinforcedplasticblock:3>,
	<mekanism:reinforcedplasticblock:4>,
	<mekanism:reinforcedplasticblock:5>,
	<mekanism:reinforcedplasticblock:6>,
	<mekanism:reinforcedplasticblock:7>,
	<mekanism:reinforcedplasticblock:8>,
	<mekanism:reinforcedplasticblock:9>,
	<mekanism:reinforcedplasticblock:10>,
	<mekanism:reinforcedplasticblock:11>,
	<mekanism:reinforcedplasticblock:12>,
	<mekanism:reinforcedplasticblock:13>,
	<mekanism:reinforcedplasticblock:14>,
	<mekanism:reinforcedplasticblock:15>,
	<mekanism:roadplasticblock>,
	<mekanism:roadplasticblock:1>,
	<mekanism:roadplasticblock:2>,
	<mekanism:roadplasticblock:3>,
	<mekanism:roadplasticblock:4>,
	<mekanism:roadplasticblock:5>,
	<mekanism:roadplasticblock:6>,
	<mekanism:roadplasticblock:7>,
	<mekanism:roadplasticblock:8>,
	<mekanism:roadplasticblock:9>,
	<mekanism:roadplasticblock:10>,
	<mekanism:roadplasticblock:11>,
	<mekanism:roadplasticblock:12>,
	<mekanism:roadplasticblock:13>,
	<mekanism:roadplasticblock:14>,
	<mekanism:roadplasticblock:15>,
	<mekanism:robit>,
	<mekanism:robit>.withTag({mekData: {energyStored: 100000.0}}),
	<mekanism:scubatank>,
	<mekanism:scubatank>.withTag({mekData: {stored: {amount: 24000, gasName: "oxygen"}}}),
	<mekanism:seismicreader>,
	<mekanism:seismicreader>.withTag({mekData: {energyStored: 12000.0}}),
	<mekanism:shard>,
	<mekanism:shard:1>,
	<mekanism:shard:2>,
	<mekanism:shard:3>,
	<mekanism:shard:4>,
	<mekanism:shard:5>,
	<mekanism:shard:6>,
	<mekanism:slickplasticblock>,
	<mekanism:slickplasticblock:1>,
	<mekanism:slickplasticblock:2>,
	<mekanism:slickplasticblock:3>,
	<mekanism:slickplasticblock:4>,
	<mekanism:slickplasticblock:5>,
	<mekanism:slickplasticblock:6>,
	<mekanism:slickplasticblock:7>,
	<mekanism:slickplasticblock:8>,
	<mekanism:slickplasticblock:9>,
	<mekanism:slickplasticblock:10>,
	<mekanism:slickplasticblock:11>,
	<mekanism:slickplasticblock:12>,
	<mekanism:slickplasticblock:13>,
	<mekanism:slickplasticblock:14>,
	<mekanism:slickplasticblock:15>,
	<mekanism:speedupgrade>,
	<mekanism:substrate>,
	<mekanism:teleportationcore>,
	<mekanism:tierinstaller>,
	<mekanism:tierinstaller:1>,
	<mekanism:tierinstaller:2>,
	<mekanism:tierinstaller:3>,
	<mekanism:transmitter>.withTag({tier: 0}),
	<mekanism:transmitter>.withTag({tier: 1}),
	<mekanism:transmitter>.withTag({tier: 2}),
	<mekanism:transmitter>.withTag({tier: 3}),
	<mekanism:transmitter:1>.withTag({tier: 0}),
	<mekanism:transmitter:1>.withTag({tier: 1}),
	<mekanism:transmitter:1>.withTag({tier: 2}),
	<mekanism:transmitter:1>.withTag({tier: 3}),
	<mekanism:transmitter:2>.withTag({tier: 0}),
	<mekanism:transmitter:2>.withTag({tier: 1}),
	<mekanism:transmitter:2>.withTag({tier: 2}),
	<mekanism:transmitter:2>.withTag({tier: 3}),
	<mekanism:transmitter:3>.withTag({tier: 0}),
	<mekanism:transmitter:3>.withTag({tier: 1}),
	<mekanism:transmitter:3>.withTag({tier: 2}),
	<mekanism:transmitter:3>.withTag({tier: 3}),
	<mekanism:transmitter:4>.withTag({tier: 0}),
	<mekanism:transmitter:5>.withTag({tier: 0}),
	<mekanism:transmitter:6>.withTag({tier: 0}),
	<mekanism:transmitter:6>.withTag({tier: 1}),
	<mekanism:transmitter:6>.withTag({tier: 2}),
	<mekanism:transmitter:6>.withTag({tier: 3}),
	<mekanism:walkietalkie>,
	<mekanismgenerators:generator>,
	<mekanismgenerators:generator:1>,
	<mekanismgenerators:generator:3>,
	<mekanismgenerators:generator:4>,
	<mekanismgenerators:generator:5>,
	<mekanismgenerators:generator:6>,
	<mekanismgenerators:generator:7>,
	<mekanismgenerators:generator:8>,
	<mekanismgenerators:generator:9>,
	<mekanismgenerators:generator:10>,
	<mekanismgenerators:generator:11>,
	<mekanismgenerators:generator:12>,
	<mekanismgenerators:generator:13>,
	<mekanismgenerators:hohlraum>,
	<mekanismgenerators:hohlraum>.withTag({mekData: {stored: {amount: 10, gasName: "fusionfuel"}}}),
	<mekanismgenerators:reactor>,
	<mekanismgenerators:reactor:1>,
	<mekanismgenerators:reactor:2>,
	<mekanismgenerators:reactor:3>,
	<mekanismgenerators:reactorglass>,
	<mekanismgenerators:reactorglass:1>,
	<mekanismgenerators:solarpanel>,
	<mekanismgenerators:turbineblade>,
	<mts:mts.charger>,
	<mts:mts.custombench>,
	<mts:mts.decorbench>,
	<mts:mts.enginebench>,
	<mts:mts.fuelhose>,
	<mts:mts.fuelpump>,
	<mts:mts.gunbench>,
	<mts:mts.handbook_car>,
	<mts:mts.handbook_plane>,
	<mts:mts.instrumentbench>,
	<mts:mts.invisible_seat>,
	<mts:mts.invisible_standing>,
	<mts:mts.invisible_wheel>,
	<mts:mts.itembench>,
	<mts:mts.jerrycan>,
	<mts:mts.jumpercable>,
	<mts:mts.jumperpack>,
	<mts:mts.key>,
	<mts:mts.paintgun>,
	<mts:mts.partscanner>,
	<mts:mts.propellerbench>,
	<mts:mts.seatbench>,
	<mts:mts.ticket>,
	<mts:mts.vehiclebench>,
	<mts:mts.wheelbench>,
	<mts:mts.wrench>,
	<mts:mts.y2kbutton>,
	<mts:waywardcraft.ageria_tps12>,
	<mts:waywardcraft.burton33metrotour>,
	<mts:waywardcraft.burton35sdomestic_mattdonalds>,
	<mts:waywardcraft.burton35sdomestic_pricedecimator>,
	<mts:waywardcraft.burton35sdomestic_standard>,
	<mts:waywardcraft.burton35sfueler>,
	<mts:waywardcraft.burton35sgrace>,
	<mts:waywardcraft.burton35smarshall>,
	<mts:waywardcraft.burton99hauler_green>,
	<mts:waywardcraft.burton99hauler_orange>,
	<mts:waywardcraft.burton99trailer>,
	<mts:waywardcraft.cochranjackrabbit>,
	<mts:waywardcraft.cochranmonarch_generic>,
	<mts:waywardcraft.cochranmonarch_sirevan>,
	<mts:waywardcraft.cochrantownmaster_black>,
	<mts:waywardcraft.cochrantownmaster_blue>,
	<mts:waywardcraft.cochrantownmaster_gold>,
	<mts:waywardcraft.cochrantownmaster_green>,
	<mts:waywardcraft.cochrantownmaster_pink>,
	<mts:waywardcraft.cochrantownmaster_purple>,
	<mts:waywardcraft.cochrantownmaster_red>,
	<mts:waywardcraft.cochrantownmaster_salmon>,
	<mts:waywardcraft.cochrantownmaster_silver>,
	<mts:waywardcraft.cochrantownmaster_white>,
	<mts:waywardcraft.coleman_bluetail>,
	<mts:waywardcraft.coleman_yellowtail>,
	<mts:waywardcraft.decimotorconquest>,
	<mts:waywardcraft.decimotorvanquisher>,
	<mts:waywardcraft.dojinmunchenjitterbug>,
	<mts:waywardcraft.dojinmunchenlilderpy_regular>,
	<mts:waywardcraft.dojinmunchenlilderpy_ss>,
	<mts:waywardcraft.fmcbumpkin_blue>,
	<mts:waywardcraft.fmcbumpkin_dirt>,
	<mts:waywardcraft.fmcbumpkin_forest>,
	<mts:waywardcraft.fmcbumpkin_green>,
	<mts:waywardcraft.fmcbumpkin_moonshine>,
	<mts:waywardcraft.fmcbumpkin_sunburn>,
	<mts:waywardcraft.fmcdixon>,
	<mts:waywardcraft.fmcsprinter>,
	<mts:waywardcraft.hanks21racer>,
	<mts:waywardcraft.hanks35_blacksilver>,
	<mts:waywardcraft.hanks35_blue>,
	<mts:waywardcraft.hanks35_green>,
	<mts:waywardcraft.hanks35_pinkpurple>,
	<mts:waywardcraft.hanks35_police>,
	<mts:waywardcraft.hanks35_silverblue>,
	<mts:waywardcraft.hanks35_silvermaroon>,
	<mts:waywardcraft.hanks35_taxi>,
	<mts:waywardcraft.hanks49_cloudwhite>,
	<mts:waywardcraft.hanks49_cornflowerblue>,
	<mts:waywardcraft.hanks49_earthbrown>,
	<mts:waywardcraft.hanks49_emeraldgreen>,
	<mts:waywardcraft.hanks49_firered>,
	<mts:waywardcraft.hanks49_freshorange>,
	<mts:waywardcraft.hanks49_goldenrod>,
	<mts:waywardcraft.hanks49_navyblue>,
	<mts:waywardcraft.hanks49_plum>,
	<mts:waywardcraft.hanks49_police>,
	<mts:waywardcraft.hanks49_salmon>,
	<mts:waywardcraft.hanks49_seasideblue>,
	<mts:waywardcraft.hanks49_silverarrow>,
	<mts:waywardcraft.hanks49_smokeblack>,
	<mts:waywardcraft.hanks49_springyellow>,
	<mts:waywardcraft.hanks49_taxicab>,
	<mts:waywardcraft.hanks49_teagreen>,
	<mts:waywardcraft.hankshorselesscarriage>,
	<mts:waywardcraft.hanksmodel12>,
	<mts:waywardcraft.hanksmodel12truck>,
	<mts:waywardcraft.henderly_h1_hummingbird>,
	<mts:waywardcraft.henderly_h2_sky_transit>,
	<mts:waywardcraft.henderly_no1flyer>,
	<mts:waywardcraft.henderly_no2flyer>,
	<mts:waywardcraft.henderly_p1_acrobat>,
	<mts:waywardcraft.henderly_p2_skipjack>,
	<mts:waywardcraft.henderly_p3_adventurer_black>,
	<mts:waywardcraft.henderly_p3_adventurer_blue>,
	<mts:waywardcraft.henderly_p3_adventurer_green>,
	<mts:waywardcraft.henderly_p3_adventurer_red>,
	<mts:waywardcraft.henderly_p3_adventurer_stock>,
	<mts:waywardcraft.henderly_p4_poseidon>,
	<mts:waywardcraft.henderly_p5_emperor_blue>,
	<mts:waywardcraft.henderly_p5_emperor_green>,
	<mts:waywardcraft.henderly_p5_emperor_military>,
	<mts:waywardcraft.landship>,
	<mts:waywardcraft.landshipgun>,
	<mts:waywardcraft.landshipturret>,
	<mts:waywardcraft.mr1_llama>,
	<mts:waywardcraft.mr2_llamaexpress>,
	<mts:waywardcraft.mr3_cardinal_green>,
	<mts:waywardcraft.mr3_cardinal_red>,
	<mts:waywardcraft.mr3_cardinal_tan>,
	<mts:waywardcraft.mr4_superllama>,
	<mts:waywardcraft.mr5_trimotor>,
	<mts:waywardcraft.mr6_cygnus>,
	<mts:waywardcraft.murphy_harpy>,
	<mts:waywardcraft.schmidtd30_beige>,
	<mts:waywardcraft.schmidtd30_black>,
	<mts:waywardcraft.schmidtd30_green>,
	<mts:waywardcraft.schmidtd30_silver>,
	<mts:waywardcraft.schmidtsilberpfeileins>,
	<mts:waywardcraft.spencersteamer>,
	<mts:waywardcraft.spencersteamracer>,
	<mts:waywardcraft.terzivelocemk1>,
	<opencomputers:adapter>,
	<opencomputers:assembler>,
	<opencomputers:cable>,
	<opencomputers:capacitor>,
	<opencomputers:card:10>,
	<opencomputers:card:11>,
	<opencomputers:card:12>,
	<opencomputers:card>,
	<opencomputers:card:1>,
	<opencomputers:card:2>,
	<opencomputers:card:3>,
	<opencomputers:card:8>,
	<opencomputers:card:9>,
	<opencomputers:card:6>,
	<opencomputers:card:4>,
	<opencomputers:card:5>,
	<opencomputers:card:7>,
	<opencomputers:carpetedcapacitor>,
	<opencomputers:case1>,
	<opencomputers:case2>,
	<opencomputers:case3>,
	<opencomputers:casecreative>,
	<opencomputers:chameliumblock>,
	<opencomputers:charger>,
	<opencomputers:component:16>,
	<opencomputers:component:17>,
	<opencomputers:component:18>,
	<opencomputers:component:3>,
	<opencomputers:component:4>,
	<opencomputers:component:5>,
	<opencomputers:component>,
	<opencomputers:component:1>,
	<opencomputers:component:2>,
	<opencomputers:component:20>,
	<opencomputers:component:6>,
	<opencomputers:component:7>,
	<opencomputers:component:8>,
	<opencomputers:component:9>,
	<opencomputers:component:10>,
	<opencomputers:component:11>,
	<opencomputers:component:13>,
	<opencomputers:component:14>,
	<opencomputers:component:15>,
	<opencomputers:component:12>,
	<opencomputers:component:19>,
	<opencomputers:disassembler>,
	<opencomputers:diskdrive>,
	<opencomputers:endstone>,
	<opencomputers:geolyzer>,
	<opencomputers:hologram1>,
	<opencomputers:hologram2>,
	<opencomputers:hoverboots>,
	<opencomputers:keyboard>,
	<opencomputers:material:1>,
	<opencomputers:material:10>,
	<opencomputers:material:15>,
	<opencomputers:material:14>,
	<opencomputers:material:5>,
	<opencomputers:material:28>,
	<opencomputers:material:11>,
	<opencomputers:material>,
	<opencomputers:material:29>,
	<opencomputers:material:12>,
	<opencomputers:material:23>,
	<opencomputers:material:24>,
	<opencomputers:material:25>,
	<opencomputers:material:27>,
	<opencomputers:material:26>,
	<opencomputers:material:13>,
	<opencomputers:material:7>,
	<opencomputers:material:8>,
	<opencomputers:material:9>,
	<opencomputers:material:20>,
	<opencomputers:material:21>,
	<opencomputers:material:22>,
	<opencomputers:material:16>,
	<opencomputers:material:4>,
	<opencomputers:material:2>,
	<opencomputers:material:17>,
	<opencomputers:material:18>,
	<opencomputers:material:19>,
	<opencomputers:material:6>,
	<opencomputers:microcontroller>,
	<opencomputers:misc:1>,
	<opencomputers:microcontroller>,
	<opencomputers:robot>,
	<opencomputers:misc>,
	<opencomputers:hoverboots>.withTag({"oc:charge": 15000.0}),
	<opencomputers:storage:1>,
    <opencomputers:motionsensor>,
	<opencomputers:netsplitter>,
	<opencomputers:powerconverter>,
	<opencomputers:powerdistributor>,
	<opencomputers:print>,
	<opencomputers:printer>,
	<opencomputers:rack>,
	<opencomputers:raid>,
	<opencomputers:redstone>,
	<opencomputers:relay>,
	<opencomputers:robot>,
	<opencomputers:robotafterimage>,
	<opencomputers:screen1>,
	<opencomputers:screen2>,
	<opencomputers:screen3>,
	<opencomputers:storage>,
	<opencomputers:storage:1>,
	<opencomputers:storage:2>,
	<opencomputers:storage:3>,
	<opencomputers:storage:4>,
	<opencomputers:tool>,
	<opencomputers:tool:1>,
	<opencomputers:tool:4>,
	<opencomputers:tool:5>,
	<opencomputers:tool:2>,
	<opencomputers:tool:3>,
	<opencomputers:transposer>,
	<opencomputers:upgrade:32>,
	<opencomputers:upgrade>,
	<opencomputers:upgrade:1>,
	<opencomputers:upgrade:2>,
	<opencomputers:upgrade:3>,
	<opencomputers:upgrade:4>,
	<opencomputers:upgrade:5>,
	<opencomputers:upgrade:6>,
	<opencomputers:upgrade:7>,
	<opencomputers:upgrade:8>,
	<opencomputers:upgrade:9>,
	<opencomputers:upgrade:10>,
	<opencomputers:upgrade:11>,
	<opencomputers:upgrade:12>,
	<opencomputers:upgrade:13>,
	<opencomputers:upgrade:14>,
	<opencomputers:upgrade:15>,
	<opencomputers:upgrade:16>,
	<opencomputers:upgrade:27>,
	<opencomputers:upgrade:28>,
	<opencomputers:upgrade:17>,
	<opencomputers:upgrade:18>,
	<opencomputers:upgrade:26>,
	<opencomputers:upgrade:30>,
	<opencomputers:upgrade:19>,
	<opencomputers:upgrade:20>,
	<opencomputers:upgrade:21>,
	<opencomputers:upgrade:22>,
	<opencomputers:upgrade:33>,
	<opencomputers:upgrade:23>,
	<opencomputers:upgrade:24>,
	<opencomputers:upgrade:25>,
	<opencomputers:upgrade:29>,
	<opencomputers:upgrade:31>,
	<opencomputers:waypoint>,
	<opencomputers:wrench>,
	<projectred-core:drawplate>,
	<projectred-core:multimeter>,
	<projectred-core:resource_item>,
	<projectred-core:resource_item:1>,
	<projectred-core:resource_item:2>,
	<projectred-core:resource_item:3>,
	<projectred-core:resource_item:4>,
	<projectred-core:resource_item:10>,
	<projectred-core:resource_item:11>,
	<projectred-core:resource_item:12>,
	<projectred-core:resource_item:20>,
	<projectred-core:resource_item:21>,
	<projectred-core:resource_item:100>,
	<projectred-core:resource_item:101>,
	<projectred-core:resource_item:102>,
	<projectred-core:resource_item:103>,
	<projectred-core:resource_item:104>,
	<projectred-core:resource_item:105>,
	<projectred-core:resource_item:250>,
	<projectred-core:resource_item:251>,
	<projectred-core:resource_item:252>,
	<projectred-core:resource_item:300>,
	<projectred-core:resource_item:301>,
	<projectred-core:resource_item:310>,
	<projectred-core:resource_item:311>,
	<projectred-core:resource_item:312>,
	<projectred-core:resource_item:320>,
	<projectred-core:resource_item:341>,
	<projectred-core:resource_item:342>,
	<projectred-core:resource_item:400>,
	<projectred-core:resource_item:401>,
	<projectred-core:resource_item:402>,
	<projectred-core:resource_item:410>,
	<projectred-core:resource_item:420>,
	<projectred-core:resource_item:421>,
	<projectred-core:resource_item:500>,
	<projectred-core:resource_item:501>,
	<projectred-core:resource_item:502>,
	<projectred-core:resource_item:503>,
	<projectred-core:resource_item:504>,
	<projectred-core:resource_item:505>,
	<projectred-core:resource_item:506>,
	<projectred-core:resource_item:507>,
	<projectred-core:resource_item:508>,
	<projectred-core:resource_item:509>,
	<projectred-core:resource_item:510>,
	<projectred-core:resource_item:511>,
	<projectred-core:resource_item:512>,
	<projectred-core:resource_item:513>,
	<projectred-core:resource_item:514>,
	<projectred-core:resource_item:515>,
	<projectred-core:resource_item:600>,
	<projectred-core:screwdriver>,
	<storagenetwork:collector_remote>,
	<storagenetwork:controller>,
	<storagenetwork:ex_kabel>,
	<storagenetwork:im_kabel>,
	<storagenetwork:inventory>,
	<storagenetwork:kabel>,
	<storagenetwork:master>,
	<storagenetwork:picker_remote>,
	<storagenetwork:process_kabel>,
	<storagenetwork:remote>,
	<storagenetwork:request>,
	<storagenetwork:simple_kabel>,
	<storagenetwork:storage_kabel>,
	<storagenetwork:upgrade>,
	<storagenetwork:upgrade:1>,
	<storagenetwork:upgrade:2>,
	<storagenetwork:upgrade:3>,
	<xnet:advanced_connector>.withTag({display: {LocName: "tile.xnet.advanced_connector_blue.name"}}),
	<xnet:advanced_connector:1>.withTag({display: {LocName: "tile.xnet.advanced_connector_red.name"}}),
	<xnet:advanced_connector:2>.withTag({display: {LocName: "tile.xnet.advanced_connector_yellow.name"}}),
	<xnet:advanced_connector:3>.withTag({display: {LocName: "tile.xnet.advanced_connector_green.name"}}),
	<xnet:antenna>,
	<xnet:antenna_base>,
	<xnet:antenna_dish>,
	<xnet:connector>.withTag({display: {LocName: "tile.xnet.connector_blue.name"}}),
	<xnet:connector:1>.withTag({display: {LocName: "tile.xnet.connector_red.name"}}),
	<xnet:connector:2>.withTag({display: {LocName: "tile.xnet.connector_yellow.name"}}),
	<xnet:connector:3>.withTag({display: {LocName: "tile.xnet.connector_green.name"}}),
	<xnet:connector:4>.withTag({display: {LocName: "tile.xnet.connector_routing.name"}}),
	<xnet:connector_upgrade>,
	<xnet:controller>,
	<xnet:facade>,
	<xnet:netcable>.withTag({display: {LocName: "tile.xnet.netcable_blue.name"}}),
	<xnet:netcable:1>.withTag({display: {LocName: "tile.xnet.netcable_red.name"}}),
	<xnet:netcable:2>.withTag({display: {LocName: "tile.xnet.netcable_yellow.name"}}),
	<xnet:netcable:3>.withTag({display: {LocName: "tile.xnet.netcable_green.name"}}),
	<xnet:netcable:4>.withTag({display: {LocName: "tile.xnet.netcable_routing.name"}}),
	<xnet:redstone_proxy>,
	<xnet:redstone_proxy_upd>,
	<xnet:router>,
	<xnet:wireless_router>,
	<xnet:xnet_manual>,
];


for entry in modernIngredients{
    mods.ItemStages.addItemStage("modern", entry);
    mods.recipestages.Recipes.setRecipeStage("modern", entry);
}