mods.jmapstages.JMapStages.setWaypointStage("exploration");
mods.jmapstages.JMapStages.setFullscreenStage("exploration");
mods.jmapstages.JMapStages.setDeathpointStage("exploration");
mods.jmapstages.JMapStages.setMinimapStage("exploration");

mods.ItemStages.addItemStage("modern", <animania:block_hamster_wheel>);
mods.ItemStages.addItemStage("modern", <bibliocraft:handdrill>);
mods.ItemStages.addItemStage("modern", <bibliocraft:discrack>);
mods.ItemStages.addItemStage("modern", <bibliocraft:cookiejar>);
mods.ItemStages.addItemStage("modern", <bibliocraft:tape>);
mods.ItemStages.addItemStage("modern", <bibliocraft:tapemeasure>);
mods.ItemStages.addItemStage("modern", <bibliocraft:dinnerplate>);

mods.ItemStages.addItemStage("modern", <cookingforblockheads:fridge>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:heating_unit>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:ice_unit>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:kitchen_floor>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:oven>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:preservation_chamber>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:sink>);
mods.ItemStages.addItemStage("modern", <cookingforblockheads:toaster>);

mods.ItemStages.stageModItems("modern","immersivepetroleum");
mods.ItemStages.stageModItems("future","mekanismgenerators");
mods.ItemStages.stageModItems("future","mts");
mods.ItemStages.stageModItems("future","opencomputers");
mods.ItemStages.stageModItems("future","projectred-core");
mods.ItemStages.stageModItems("future","projectred-fabrication");
mods.ItemStages.stageModItems("future","projectred-integration");
mods.ItemStages.stageModItems("future","projectred-transmission");
mods.ItemStages.stageModItems("future","scannable");
mods.ItemStages.stageModItems("future","storagenetwork");
mods.ItemStages.stageModItems("future","xnet");

mods.ItemStages.addItemStage("modern", <minecraft:concrete:1>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:2>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:3>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:4>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:5>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:6>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:7>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:8>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:9>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:10>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:11>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:12>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:13>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:14>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete:15>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:1>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:2>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:3>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:4>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:5>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:6>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:7>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:8>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:9>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:10>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:11>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:12>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:13>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:14>);
mods.ItemStages.addItemStage("modern", <minecraft:concrete_powder:15>);

mods.ItemStages.addItemStage("modern", <ancientwarfarenpc:shield_round_5> );
mods.ItemStages.addItemStage("modern", <ancientwarfarenpc:shield_round_6> );
mods.ItemStages.addItemStage("modern", <ancientwarfarenpc:shield_tribal_1> );
mods.ItemStages.addItemStage("modern", <ancientwarfarenpc:shield_tribal_2> );
mods.ItemStages.addItemStage("modern", <ancientwarfarevehicle:ammo_canister_shot_10> );
mods.ItemStages.addItemStage("modern", <bibliocraft:bibliodrill> );
mods.ItemStages.addItemStage("modern", <bibliocraft:clipboard> );
mods.ItemStages.addItemStage("modern", <chisel:auto_chisel> );
mods.ItemStages.addItemStage("modern", <cookingforblockheads:fridge> );
mods.ItemStages.addItemStage("modern", <cookingforblockheads:heating_unit> );
mods.ItemStages.addItemStage("modern", <cookingforblockheads:ice_unit> );
mods.ItemStages.addItemStage("modern", <cookingforblockheads:kitchen_floor> );
mods.ItemStages.addItemStage("modern", <cookingforblockheads:oven> );
mods.ItemStages.addItemStage("modern", <cookingforblockheads:toaster> );
mods.ItemStages.addItemStage("modern", <culinaryconstruct:sandwich_station> );
mods.ItemStages.addItemStage("modern", <forestry:analyzer> );
mods.ItemStages.addItemStage("modern", <forestry:arboretum> );
mods.ItemStages.addItemStage("modern", <forestry:can> );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "water", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "lava", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "iron", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "gold", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "pigiron", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "cobalt", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ardite", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "manyullyn", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "knightslime", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "alubrass", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "brass", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "copper", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "tin", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "bronze", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "zinc", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "lead", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "nickel", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "silver", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "electrum", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "steel", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "aluminum", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidhydrogen", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidoxygen", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidchlorine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidsulfurdioxide", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidsulfurtrioxide", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "sulfuricacid", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidhydrogenchloride", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidethene", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidsodium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "brine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquiddeuterium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidtritium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidfusionfuel", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquidlithium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "heavywater", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "steam", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "peach_juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "pear_juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "persimmon_juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "peach_schnapps", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "perry", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "persimmon_wine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "sand", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "blood", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "poison", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "hot_spring_water", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "fierymetal", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "knightmetal", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "fiery_essence", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "slop", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk_holstein", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk_friesian", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk_jersey", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk_goat", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk_sheep", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "animania_honey", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "molten_neptunium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "molten_cheese", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "molten_cold_iron", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "creosote", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "plantoil", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ethanol", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "biodiesel", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "concrete", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "potion", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "uranium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "constantan", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "purified_water", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "bio.ethanol", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "biomass", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "glass", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "for.honey", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "seed.oil", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "short.mead", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "oliveoil", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ironberryjuice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "wildberryjuice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "grapejuice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "applejuice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "alewort", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ale", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "cider", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ironwine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "mead", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "wildberrywine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "wine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "oil", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "diesel", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "lubricant", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "napalm", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "dist_water", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "xpjuice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "cinderfire_wort", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "shimmerdew_wort", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "viscous_wort", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "cinderfire_whiskey", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "shimmerdew_spirits", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "viscous_brew", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "juniper_berry_juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "elderberry_juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "wormwood_mixture", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "sage_juice", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "gin", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "elderberry_wine", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "absinthe", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "sage_liqueur", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "titanium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "iridium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "platinum", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "invar", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "amethyst", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ruby", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "sapphire", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "peridot", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "osmium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "thaumium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "kovar", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "lavium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "qivium", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "chocolate_liquor", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "milk_chocolate", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "dark_chocolate", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "flux_goo", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "liquid_death", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "purifying_fluid", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "stone", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "obsidian", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "clay", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "dirt", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "emerald", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "blueslime", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "purpleslime", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "tannin", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "urushi", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "brine_netjry", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "waste", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "bitumen", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "bitumen_boiling", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "paraffin", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "magma_basaltic", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "ovis_atre_milk", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:can:1>.withTag({Fluid: {FluidName: "smoke", Amount: 1000}}) );
mods.ItemStages.addItemStage("modern", <forestry:chipsets>.withTag({T: 0 as short}) );
mods.ItemStages.addItemStage("modern", <forestry:chipsets:1>.withTag({T: 1 as short}) );
mods.ItemStages.addItemStage("modern", <forestry:chipsets:2>.withTag({T: 2 as short}) );
mods.ItemStages.addItemStage("modern", <forestry:chipsets:3>.withTag({T: 3 as short}) );
mods.ItemStages.addItemStage("modern", <forestry:climatiser> );
mods.ItemStages.addItemStage("modern", <forestry:crafting_material:4> );
mods.ItemStages.addItemStage("modern", <forestry:crate> );
mods.ItemStages.addItemStage("modern", <forestry:database> );
mods.ItemStages.addItemStage("modern", <forestry:fabricator> );
mods.ItemStages.addItemStage("modern", <forestry:farm_crops> );
mods.ItemStages.addItemStage("modern", <forestry:farm_ender> );
mods.ItemStages.addItemStage("modern", <forestry:farm_gourd> );
mods.ItemStages.addItemStage("modern", <forestry:farm_mushroom> );
mods.ItemStages.addItemStage("modern", <forestry:farm_nether> );
mods.ItemStages.addItemStage("modern", <forestry:fermenter> );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 0}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 1}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 2}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 3}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 4}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 5}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 6}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 7}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 8}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 9}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm>.withTag({FarmBlock: 10}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 0}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 1}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 2}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 3}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 4}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 5}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 6}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 7}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 8}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 9}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:2>.withTag({FarmBlock: 10}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 0}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 1}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 2}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 3}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 4}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 5}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 6}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 7}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 8}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 9}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:3>.withTag({FarmBlock: 10}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 0}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 1}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 2}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 3}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 4}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 5}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 6}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 7}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 8}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 9}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:4>.withTag({FarmBlock: 10}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 0}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 1}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 2}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 3}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 4}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 5}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 6}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 7}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 8}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 9}) );
mods.ItemStages.addItemStage("modern", <forestry:ffarm:5>.withTag({FarmBlock: 10}) );
mods.ItemStages.addItemStage("modern", <forestry:flexible_casing> );
mods.ItemStages.addItemStage("modern", <forestry:fluid.bio.ethanol> );
mods.ItemStages.addItemStage("modern", <forestry:fluid.biomass> );
mods.ItemStages.addItemStage("modern", <forestry:genetic_filter> );
mods.ItemStages.addItemStage("modern", <forestry:habitat_former> );
mods.ItemStages.addItemStage("modern", <forestry:habitat_screen> );
mods.ItemStages.addItemStage("modern", <forestry:hardened_machine> );
mods.ItemStages.addItemStage("modern", <forestry:iodine_capsule> );
mods.ItemStages.addItemStage("modern", <forestry:mailbox> );
mods.ItemStages.addItemStage("modern", <forestry:portable_alyzer> );
mods.ItemStages.addItemStage("modern", <forestry:rainmaker> );
mods.ItemStages.addItemStage("modern", <forestry:soldering_iron> );
mods.ItemStages.addItemStage("modern", <forestry:stamps> );
mods.ItemStages.addItemStage("modern", <forestry:stamps:1> );
mods.ItemStages.addItemStage("modern", <forestry:stamps:2> );
mods.ItemStages.addItemStage("modern", <forestry:stamps:3> );
mods.ItemStages.addItemStage("modern", <forestry:stamps:4> );
mods.ItemStages.addItemStage("modern", <forestry:stamps:5> );
mods.ItemStages.addItemStage("modern", <forestry:stamps:6> );
mods.ItemStages.addItemStage("modern", <forestry:still> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:1> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:2> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:4> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:5> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:6> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:7> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:9> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:10> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:11> );
mods.ItemStages.addItemStage("modern", <forestry:thermionic_tubes:12> );
mods.ItemStages.addItemStage("modern", <forestry:trade_station> );
mods.ItemStages.addItemStage("modern", <grapplemod:repeller> );
mods.ItemStages.addItemStage("modern", <grapplemod:rocketdoublemotorhook>);
mods.ItemStages.addItemStage("modern", <grapplemod:rockethook>);
mods.ItemStages.addItemStage("modern", <grapplemod:rocketupgradeitem> );
mods.ItemStages.addItemStage("modern", <grapplemod:smarthook>);
mods.ItemStages.addItemStage("modern", <immersivepetroleum:dummy> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:material> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:metal_device> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:metal_device:1> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:metal_multiblock> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:oil_can> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:CokeOven"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:AlloySmelter"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:BlastFurnace"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:BlastFurnaceAdvanced"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:MetalPress"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Crusher"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:SheetmetalTank"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Silo"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Assembler"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:AutoWorkbench"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:BottlingMachine"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Squeezer"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Fermenter"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Refinery"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:DieselGenerator"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:ArcFurnace"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Lightningrod"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Mixer"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:Feedthrough"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IP:DistillationTower"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IP:Pumpjack"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:Distiller"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:SolarTower"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:SolarReflector"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:SteamTurbine"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:Boiler"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:Alternator"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IT:CokeOvenAdvanced"}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:schematic>.withTag({multiblock: "IE:ExcavatorDemo", flip: 1 as byte}) );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:speedboat> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:stone_decoration> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:upgrades> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:upgrades:1> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:upgrades:2> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:upgrades:3> );
mods.ItemStages.addItemStage("modern", <immersivepetroleum:upgrades:4> );
mods.ItemStages.addItemStage("modern", <malisisdoors:garage_door> );
mods.ItemStages.addItemStage("modern", <malisisdoors:iron_sliding_door> );
mods.ItemStages.addItemStage("modern", <malisisdoors:laboratory_door> );
mods.ItemStages.addItemStage("modern", <malisisdoors:rustyhandle> );
mods.ItemStages.addItemStage("modern", <malisisdoors:rustyhatch> );
mods.ItemStages.addItemStage("modern", <malisisdoors:rustyladder> );
mods.ItemStages.addItemStage("modern", <malisisdoors:sliding_trapdoor> );
mods.ItemStages.addItemStage("modern", <mcwbridges:most1> );
mods.ItemStages.addItemStage("modern", <mcwbridges:most2> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:5> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:6>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:6>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:6>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:6>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:6>.withTag({tier: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:7> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:1> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:2> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:3>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:3>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:3>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:3>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:4>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:4>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:4>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:4>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:5> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:6> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:7> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:8> );
mods.ItemStages.addItemStage("modern", <mekanism:basicblock2:9> );
mods.ItemStages.addItemStage("modern", <mekanism:biofuel> );
mods.ItemStages.addItemStage("modern", <mekanism:boundingblock> );
mods.ItemStages.addItemStage("modern", <mekanism:cardboardbox> );
mods.ItemStages.addItemStage("modern", <mekanism:clump> );
mods.ItemStages.addItemStage("modern", <mekanism:clump:1> );
mods.ItemStages.addItemStage("modern", <mekanism:clump:2> );
mods.ItemStages.addItemStage("modern", <mekanism:clump:3> );
mods.ItemStages.addItemStage("modern", <mekanism:clump:4> );
mods.ItemStages.addItemStage("modern", <mekanism:clump:5> );
mods.ItemStages.addItemStage("modern", <mekanism:clump:6> );
mods.ItemStages.addItemStage("modern", <mekanism:compressedcarbon> );
mods.ItemStages.addItemStage("modern", <mekanism:compresseddiamond> );
mods.ItemStages.addItemStage("modern", <mekanism:compressedobsidian> );
mods.ItemStages.addItemStage("modern", <mekanism:compressedredstone> );
mods.ItemStages.addItemStage("modern", <mekanism:configurationcard> );
mods.ItemStages.addItemStage("modern", <mekanism:configurator> );
mods.ItemStages.addItemStage("modern", <mekanism:configurator>.withTag({mekData: {energyStored: 60000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:controlcircuit> );
mods.ItemStages.addItemStage("modern", <mekanism:controlcircuit:1> );
mods.ItemStages.addItemStage("modern", <mekanism:controlcircuit:2> );
mods.ItemStages.addItemStage("modern", <mekanism:controlcircuit:3> );
mods.ItemStages.addItemStage("modern", <mekanism:craftingformula> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal:1> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal:2> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal:3> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal:4> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal:5> );
mods.ItemStages.addItemStage("modern", <mekanism:crystal:6> );
mods.ItemStages.addItemStage("modern", <mekanism:dictionary> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust:1> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust:2> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust:3> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust:4> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust:5> );
mods.ItemStages.addItemStage("modern", <mekanism:dirtydust:6> );
mods.ItemStages.addItemStage("modern", <mekanism:dust> );
mods.ItemStages.addItemStage("modern", <mekanism:dust:1> );
mods.ItemStages.addItemStage("modern", <mekanism:dust:2> );
mods.ItemStages.addItemStage("modern", <mekanism:dust:3> );
mods.ItemStages.addItemStage("modern", <mekanism:dust:4> );
mods.ItemStages.addItemStage("modern", <mekanism:dust:5> );
mods.ItemStages.addItemStage("modern", <mekanism:dust:6> );
mods.ItemStages.addItemStage("modern", <mekanism:electricbow> );
mods.ItemStages.addItemStage("modern", <mekanism:electricbow>.withTag({mekData: {energyStored: 120000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:electrolyticcore> );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 0, mekData: {energyStored: 2000000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 1, mekData: {energyStored: 8000000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 2, mekData: {energyStored: 3.2E7}}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}) );
mods.ItemStages.addItemStage("modern", <mekanism:energytablet> );
mods.ItemStages.addItemStage("modern", <mekanism:energytablet>.withTag({mekData: {energyStored: 1000000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:energyupgrade> );
mods.ItemStages.addItemStage("modern", <mekanism:enrichedalloy> );
mods.ItemStages.addItemStage("modern", <mekanism:enrichediron> );
mods.ItemStages.addItemStage("modern", <mekanism:filterupgrade> );
mods.ItemStages.addItemStage("modern", <mekanism:flamethrower> );
mods.ItemStages.addItemStage("modern", <mekanism:flamethrower>.withTag({mekData: {stored: {amount: 24000, gasName: "hydrogen"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:freerunners> );
mods.ItemStages.addItemStage("modern", <mekanism:freerunners>.withTag({mekData: {energyStored: 64000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gasmask> );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogen"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "oxygen"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "water"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "chlorine"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurdioxide"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurtrioxide"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfuricacid"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogenchloride"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "ethene"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sodium"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "brine"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "deuterium"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "tritium"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "fusionfuel"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "lithium"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:gasupgrade> );
mods.ItemStages.addItemStage("modern", <mekanism:gaugedropper> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:1> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:2> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:3> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:4> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:5> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:6> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:7> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:8> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:9> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:10> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:11> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:12> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:13> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:14> );
mods.ItemStages.addItemStage("modern", <mekanism:glowpanel:15> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:1> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:3> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:5> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:6> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:7> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:13> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:glowplasticblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot:1> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot:2> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot:3> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot:4> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot:5> );
mods.ItemStages.addItemStage("modern", <mekanism:ingot:6> );
mods.ItemStages.addItemStage("modern", <mekanism:itemproxy> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:1> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:3> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 5}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 6}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 7}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:5>.withTag({recipeType: 8}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 5}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 6}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 7}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:6>.withTag({recipeType: 8}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 5}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 6}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 7}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:7>.withTag({recipeType: 8}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:13> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:1> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:2> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:3> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:4> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:5> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:6> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:7> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:8> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:9> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:10> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:11>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:11>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:11>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:11>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:11>.withTag({tier: 4}) );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:12> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:13> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:14> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock2:15> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock3> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock3:1> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock3:3> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock3:4> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock3:5> );
mods.ItemStages.addItemStage("modern", <mekanism:machineblock3:6> );
mods.ItemStages.addItemStage("modern", <mekanism:mufflingupgrade> );
mods.ItemStages.addItemStage("modern", <mekanism:networkreader> );
mods.ItemStages.addItemStage("modern", <mekanism:networkreader>.withTag({mekData: {energyStored: 60000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:nugget> );
mods.ItemStages.addItemStage("modern", <mekanism:nugget:1> );
mods.ItemStages.addItemStage("modern", <mekanism:nugget:3> );
mods.ItemStages.addItemStage("modern", <mekanism:nugget:4> );
mods.ItemStages.addItemStage("modern", <mekanism:nugget:5> );
mods.ItemStages.addItemStage("modern", <mekanism:obsidiantnt> );
mods.ItemStages.addItemStage("modern", <mekanism:otherdust> );
mods.ItemStages.addItemStage("modern", <mekanism:otherdust:1> );
mods.ItemStages.addItemStage("modern", <mekanism:otherdust:3> );
mods.ItemStages.addItemStage("modern", <mekanism:otherdust:4> );
mods.ItemStages.addItemStage("modern", <mekanism:otherdust:5> );
mods.ItemStages.addItemStage("modern", <mekanism:otherdust:6> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:1> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:3> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:5> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:6> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:7> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:13> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:1> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:2> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:3> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:4> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:5> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:6> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:7> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:8> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:9> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:10> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:11> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:12> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:13> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:14> );
mods.ItemStages.addItemStage("modern", <mekanism:plasticfence:15> );
mods.ItemStages.addItemStage("modern", <mekanism:polyethene> );
mods.ItemStages.addItemStage("modern", <mekanism:polyethene:1> );
mods.ItemStages.addItemStage("modern", <mekanism:polyethene:2> );
mods.ItemStages.addItemStage("modern", <mekanism:polyethene:3> );
mods.ItemStages.addItemStage("modern", <mekanism:portableteleporter> );
mods.ItemStages.addItemStage("modern", <mekanism:portableteleporter>.withTag({mekData: {energyStored: 1000000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedalloy> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:1> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:3> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:5> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:6> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:7> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:13> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:reinforcedplasticblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:1> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:3> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:5> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:6> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:7> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:13> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:roadplasticblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:robit> );
mods.ItemStages.addItemStage("modern", <mekanism:robit>.withTag({mekData: {energyStored: 100000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:salt> );
mods.ItemStages.addItemStage("modern", <mekanism:saltblock> );
mods.ItemStages.addItemStage("modern", <mekanism:sawdust> );
mods.ItemStages.addItemStage("modern", <mekanism:scubatank> );
mods.ItemStages.addItemStage("modern", <mekanism:scubatank>.withTag({mekData: {stored: {amount: 24000, gasName: "oxygen"}}}) );
mods.ItemStages.addItemStage("modern", <mekanism:seismicreader> );
mods.ItemStages.addItemStage("modern", <mekanism:seismicreader>.withTag({mekData: {energyStored: 12000.0}}) );
mods.ItemStages.addItemStage("modern", <mekanism:shard> );
mods.ItemStages.addItemStage("modern", <mekanism:shard:1> );
mods.ItemStages.addItemStage("modern", <mekanism:shard:2> );
mods.ItemStages.addItemStage("modern", <mekanism:shard:3> );
mods.ItemStages.addItemStage("modern", <mekanism:shard:4> );
mods.ItemStages.addItemStage("modern", <mekanism:shard:5> );
mods.ItemStages.addItemStage("modern", <mekanism:shard:6> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:1> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:2> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:3> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:4> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:5> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:6> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:7> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:8> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:9> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:10> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:11> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:12> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:13> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:14> );
mods.ItemStages.addItemStage("modern", <mekanism:slickplasticblock:15> );
mods.ItemStages.addItemStage("modern", <mekanism:speedupgrade> );
mods.ItemStages.addItemStage("modern", <mekanism:substrate> );
mods.ItemStages.addItemStage("modern", <mekanism:teleportationcore> );
mods.ItemStages.addItemStage("modern", <mekanism:tierinstaller> );
mods.ItemStages.addItemStage("modern", <mekanism:tierinstaller:1> );
mods.ItemStages.addItemStage("modern", <mekanism:tierinstaller:2> );
mods.ItemStages.addItemStage("modern", <mekanism:tierinstaller:3> );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:1>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:1>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:1>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:1>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:2>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:2>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:2>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:2>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:3>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:3>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:3>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:3>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:4>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:5>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:6>.withTag({tier: 0}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:6>.withTag({tier: 1}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:6>.withTag({tier: 2}) );
mods.ItemStages.addItemStage("modern", <mekanism:transmitter:6>.withTag({tier: 3}) );
mods.ItemStages.addItemStage("modern", <mekanism:walkietalkie> );
mods.ItemStages.addItemStage("modern", <tcomplement:materials:6> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_glass> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:1> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:2> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:3> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:4> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:5> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:6> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:7> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:8> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:9> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:10> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:11> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:12> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:13> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:14> );
mods.ItemStages.addItemStage("modern", <tconstruct:clear_stained_glass:15> );
mods.ItemStages.addItemStage("modern", <toughasnails:temperature_coil> );
mods.ItemStages.addItemStage("modern", <toughasnails:temperature_coil:1> );
